import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const home=mkdtempSync(join(tmpdir(),'qwen-config-synthetic-'));
process.env.HOME=home;process.env.QWEN_HOME=home;process.env.QWEN_RUNTIME_DIR=home;
const { Config, deriveConfig } = await import((await import('node:url')).pathToFileURL(join(process.argv[2]||'__required_explicit_qwen_root__','packages/core/dist/src/config/config.js')).href);
const params={sessionId:'synthetic-config',sessionToolAllowlist:['read','write'],targetDir:process.cwd(),cwd:process.cwd(),debugMode:false,telemetry:{enabled:false},deferTelemetryInitialization:true,usageStatisticsEnabled:false,disableAllHooks:true,bareMode:true};
try {
const c=new Config(params);
assert.deepEqual(c.getSessionToolAllowlist(),['read','write']);
const child=deriveConfig(c,{getSessionToolAllowlist:()=>['read','shell']});
assert.deepEqual(child.getSessionToolAllowlist(),['read']);
assert.throws(()=>Object.defineProperty(child,'getSessionToolAllowlist',{value:()=>['shell']}));
const grandchild=deriveConfig(child,{getSessionToolAllowlist:()=>['write','shell']});
assert.deepEqual(grandchild.getSessionToolAllowlist(),[]);
assert.throws(()=>new Config({...params,sessionToolAllowlist:undefined}),/explicit array/);
new Config({...params,sessionToolAllowlist:['read']});
const resumed=new Config({...params,sessionPolicySourceId:'synthetic-config'});
assert.deepEqual(resumed.getSessionToolAllowlist(),['read']);
const fork=new Config({...params,sessionId:'synthetic-fork',sessionPolicySourceId:'synthetic-config'});
assert.deepEqual(fork.getSessionToolAllowlist(),['read']);
assert.throws(()=>new Config({...params,sessionId:'synthetic-missing',sessionPolicySourceId:'missing'}));
assert.throws(()=>c.startNewSession('other'),/fresh host process/);
const { SubagentManager }=await import((await import('node:url')).pathToFileURL(join(process.argv[2]||'__required_explicit_qwen_root__','packages/core/dist/src/subagents/subagent-manager.js')).href);
const manager=new SubagentManager(c);
await assert.rejects(()=>manager.createAgentHeadless({name:'synthetic-external',executor:{kind:'codex'}},c),/Managed host forbids/);
await assert.rejects(()=>manager.createAgentHeadless({name:'synthetic-mcp',mcpServers:{bad:{command:'not-executed'}}},c),/Managed host forbids/);
assert.equal(await manager.loadSubagent('synthetic-nonexistent','project'),null);
console.log(JSON.stringify({synthetic:true,realConfig:true,checks:12,passed:12,network:false}));
} finally {rmSync(home,{recursive:true,force:true});}
