// Multi-scope fixtures use attached trusted views (recover=false) under one authoritative owner. Independent runtime owners are tested as denied.
import test from 'node:test';
import Database from 'better-sqlite3';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync} from 'node:fs';
import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';
import {Store,ProductError} from '@between/core/store';
import {TurnCoordinator} from '@between/core/runtime/turn-coordinator';
import {OffCache} from '@between/core/runtime/off-cache';
import {type HostAdapter,type HostTurn,type HostEvent} from '@between/contracts/host';
// Synthetic adapter deliberately does not impersonate Qwen/real model evidence.
class SyntheticHost implements HostAdapter {
  calls=0; cancels:string[]=[]; beforeResult?:()=>Promise<void>; badContext=false; noPolicy=false; approvals=false; fail=false; noContext=false;
  constructor(private store:Store){}
  async *startTurn(input:HostTurn):AsyncIterable<HostEvent>{this.calls++;let sequence=0;const common=()=>({...input,grant:undefined,input:undefined,event_id:randomUUID(),sequence:sequence++,occurred_at:Date.now(),...(this.badContext?{conversation_id:'other'}:{})});
    if(!this.noPolicy)yield {...common(),type:'policy',sessionToolAllowlist:input.sessionToolAllowlist,hooks:'sdk_functions',registeredTools:input.sessionToolAllowlist,managed_host_contract_version:1,cli_version:'0.24.7',sdk_version:'0.1.16',policy_source:'runtime_readback'};
    if(this.approvals){yield {...common(),type:'approval',approval_id:randomUUID(),status:'pending'};return;}
    const attempt_id=randomUUID();yield {...common(),type:'attempt_started',attempt_id,attempt_index:0,reason:'initial',provider:'synthetic',model:'fixture',input:{capture_status:'disabled'}};
    if(!this.noContext)this.store.context(input.grant,{synthetic:true});if(this.beforeResult)await this.beforeResult();
    if(this.fail){yield {...common(),type:'failure',code:'HOST_DISCONNECTED',retryable:true,outcome:'definite_failure'};return;}
    yield {...common(),type:'attempt_finished',attempt_id,response_complete:true,status:'succeeded',output:{capture_status:'disabled'}};
    yield {...common(),type:'result',attempt_id,text:'SYNTHETIC 测试替身回复，不是模型结果。',response_complete:true};
  }
  resumeExecution(input:HostTurn){return this.startTurn(input);}
  async cancelTurn(id:string){this.cancels.push(id);}
  async close(){}
}
function setup(memory=true){const dir=mkdtempSync(path.join(os.tmpdir(),'qwen-coordinator-')),store=new Store(path.join(dir,'business.db'));store.start(true,true,memory);const key=Buffer.alloc(32,42),off=new OffCache(path.join(dir,'spool.db'),key,store.authority),host=new SyntheticHost(store),coordinator=new TurnCoordinator(store,host,off,key);return {dir,store,off,host,coordinator};}
async function close(s:ReturnType<typeof setup>){await s.coordinator.close();s.off.close();s.store.close();}
test('synthetic headless接受→执行→pending→重复ack幂等；事件与attempt持久',async()=>{const s=setup(),id=randomUUID();s.coordinator.accept(s.store.scope,id,'SYNTHETIC 日常');await s.coordinator.idle();const turn=s.coordinator.snapshot().turns[0];assert.equal(turn.status,'completed');assert.equal(s.store.history().at(-1)?.status,'pending');assert.equal(s.coordinator.ack(s.store.scope,id,turn.message_id!),true);assert.equal(s.coordinator.ack(s.store.scope,id,turn.message_id!),true);assert.equal(s.store.history().at(-1)?.status,'confirmed');assert.equal((s.store.db.prepare('select count(*) n from model_attempts').get() as any).n,1);await close(s);});
test('同turn重送不重复执行；不同正文明确冲突',async()=>{const s=setup(),id=randomUUID();s.coordinator.accept(s.store.scope,id,'SYNTHETIC A');await s.coordinator.idle();assert.equal(s.coordinator.accept(s.store.scope,id,'SYNTHETIC A').duplicate,true);assert.throws(()=>s.coordinator.accept(s.store.scope,id,'SYNTHETIC B'),/TURN_INPUT_CONFLICT/);assert.equal(s.host.calls,1);await close(s);});
test('同会话持久排队20项；超限返回QUEUE_FULL，不静默丢弃',async()=>{const s=setup();let release!:()=>void;const gate=new Promise<void>(r=>release=r);s.host.beforeResult=()=>gate;s.coordinator.accept(s.store.scope,randomUUID(),'SYNTHETIC 运行');for(let i=0;i<20;i++)s.coordinator.accept(s.store.scope,randomUUID(),'SYNTHETIC 排队'+i);assert.equal(s.coordinator.snapshot().turns.filter(t=>t.status==='queued').length,20);assert.throws(()=>s.coordinator.accept(s.store.scope,randomUUID(),'SYNTHETIC 超限'),/QUEUE_FULL/);for(const t of s.coordinator.snapshot().turns.filter(t=>t.status==='queued'))await s.coordinator.cancelTurn(s.store.scope,t.turn_id);for(const t of s.coordinator.snapshot().turns.filter(t=>t.status==='running'))await s.coordinator.cancelTurn(s.store.scope,t.turn_id);release();await s.coordinator.idle();assert.equal(s.host.calls,1);assert.ok(s.coordinator.snapshot().turns.every(t=>t.status==='cancelled'));await close(s);});
test('取消后重启不复活；未ack回复不复活',async()=>{const s=setup(),first=randomUUID();s.coordinator.accept(s.store.scope,first,'SYNTHETIC 完成无ack');await s.coordinator.idle();const message=s.coordinator.snapshot().turns[0].message_id!;let release!:()=>void;const gate=new Promise<void>(r=>release=r);s.host.beforeResult=()=>gate;const second=randomUUID();s.coordinator.accept(s.store.scope,second,'SYNTHETIC 取消');await s.coordinator.cancelTurn(s.store.scope,second);release();await s.coordinator.idle();const file=s.store.file;await close(s);const store=new Store(file),host=new SyntheticHost(store),coordinator=new TurnCoordinator(store,host);assert.equal(coordinator.snapshot().turns.find(t=>t.turn_id===second)?.status,'cancelled');assert.equal(coordinator.snapshot().turns.find(t=>t.turn_id===first)?.error_code,'UNCONFIRMED_OUTPUT_LOST');assert.ok(!store.history().some(m=>m.id===message));coordinator.start();await coordinator.idle();assert.equal(host.calls,0);await coordinator.close();store.close();});
test('业务提交与operation结果原子幂等，回滚与独立读回',async()=>{const s=setup(),id=randomUUID(),t=s.store.receive(id,'SYNTHETIC 我喜欢蓝色')!;s.store.context(t.token,{});const op=id+':memory';const first=s.store.remember(t.token,'我喜欢蓝色',op);assert.equal(first.state_version_before,0);assert.equal(first.state_version_after,1);assert.equal(first.readback_version,1);assert.deepEqual(s.store.remember(t.token,'我喜欢蓝色',op),first);assert.throws(()=>s.store.remember(t.token,'别的',op),/OPERATION_CONFLICT/);assert.throws(()=>s.store.operation(id+':fail',{},()=>{s.store.remember(t.token,'SYNTHETIC',id+':rollback');throw new ProductError('INJECTED');},id),/INJECTED/);assert.equal(s.store.version(),1);assert.equal((s.store.db.prepare('select count(*) n from memories').get() as any).n,1);await close(s);});
test('off加密spool无明文；处理成功清缓存；必要控制保留',async()=>{const s=setup(false),id=randomUUID();s.coordinator.accept(s.store.scope,id,'SYNTHETIC_OFF_SECRET_CANARY');await s.coordinator.idle();assert.equal((s.off.db.prepare('select count(*) n from receipts').get() as any).n,0);assert.equal((s.store.db.prepare('select body from runtime_turns').get() as any).body,null);assert.equal((s.store.db.prepare('select count(*) n from sources').get() as any).n,0);assert.ok(!readFileSync(s.store.file).includes(Buffer.from('SYNTHETIC_OFF_SECRET_CANARY')));assert.ok(!JSON.stringify(s.store.db.prepare('select * from host_event_ids').all()).includes('SYNTHETIC_OFF_SECRET_CANARY'));await close(s);});
test('缺加密能力默认off不静默落明文；关闭控制仍生效',async()=>{const s=setup(),c=new TurnCoordinator(s.store,s.host);assert.throws(()=>c.accept(s.store.scope,randomUUID(),'关闭长期记忆'),/OFF_CACHE_UNAVAILABLE/);assert.equal(s.store.controls().memory,'off');assert.equal(c.snapshot().turns.length,0);await c.close();await close(s);});
test('授权、policy、trace隔离与审批fail closed',async()=>{for(const mode of ['badContext','noPolicy','approvals'] as const){const s=setup();s.host[mode]=true;assert.throws(()=>s.coordinator.accept('foreign',randomUUID(),'SYNTHETIC'),/NOT_AUTHORIZED/);s.coordinator.accept(s.store.scope,randomUUID(),'SYNTHETIC');await s.coordinator.idle();assert.equal(s.coordinator.snapshot().turns[0].status,'failed');assert.equal(s.store.history().filter(m=>m.role==='character').length,0);await close(s);}});
test('两个会话共用SQLite时控制、来源、历史和MCP grant隔离',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'qwen-scopes-')),file=path.join(dir,'state.db'),a=new Store(file,()=>Date.now(),true,'a'),b=new Store(file,()=>Date.now(),false,'b');a.start(true,true,true);b.start(true,true,true);const ta=a.receive(randomUUID(),'A_SECRET')!,tb=b.receive(randomUUID(),'B_SECRET')!;a.context(ta.token,{});b.context(tb.token,{});assert.equal(a.history().length,1);assert.equal(b.history().length,1);assert.equal(a.history()[0].text,'A_SECRET');assert.throws(()=>a.context(tb.token,{}),/NOT_AUTHORIZED/);a.set({memory:'off'});assert.doesNotThrow(()=>b.context(tb.token,{}));a.close();b.close();});
test('旧schema只读拒绝且不改旧文件；独立新库不继承旧控制',()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'qwen-fresh-schema-')),file=path.join(dir,'old.db');const old=new Database(file);old.exec('CREATE TABLE controls(id INTEGER PRIMARY KEY,data TEXT NOT NULL)');old.prepare('INSERT INTO controls VALUES(1,?)').run(JSON.stringify({started:true,memory:'on',nickname:'SYNTHETIC_OLD'}));old.close();const before=createHash('sha256').update(readFileSync(file)).digest('hex');assert.throws(()=>new Store(file),/PRIVACY_AUTHORITY_REQUIRED/);assert.equal(createHash('sha256').update(readFileSync(file)).digest('hex'),before);const next=new Store(path.join(dir,'new-v2.db'));assert.equal(next.controls().started,false);assert.equal(next.controls().memory,'off');assert.equal(next.controls().nickname,'');next.close();});
test('跨scope同turn_id不覆盖加密spool或持久turn',async()=>{const s=setup(false),other=new Store(s.store.file,()=>Date.now(),false,'other');other.start(true,true,false);const host=new SyntheticHost(other),c=new TurnCoordinator(other,host,s.off,Buffer.alloc(32,42)),id=randomUUID();s.off.put(s.store.scope,id,'SYNTHETIC_A');s.off.put('other',id,'SYNTHETIC_B');assert.equal(s.off.get(s.store.scope,id),'SYNTHETIC_A');assert.equal(s.off.get('other',id),'SYNTHETIC_B');s.coordinator.accept(s.store.scope,id,'SYNTHETIC_A');c.accept('other',id,'SYNTHETIC_B');await Promise.all([s.coordinator.idle(),c.idle()]);assert.equal((s.store.db.prepare('select count(*) n from runtime_turns').get() as any).n,2);assert.equal(s.coordinator.snapshot().turns.length,1);assert.equal(c.snapshot().turns.length,1);await c.close();other.close();await close(s);});
test('满队列停止控制仍立即生效并取消在途；队列溢出不绕过边界',async()=>{const s=setup();let release!:()=>void;const gate=new Promise<void>(r=>release=r);s.host.beforeResult=()=>gate;s.coordinator.accept(s.store.scope,randomUUID(),'SYNTHETIC运行');for(let i=0;i<20;i++)s.coordinator.accept(s.store.scope,randomUUID(),'SYNTHETIC队列'+i);assert.throws(()=>s.coordinator.accept(s.store.scope,randomUUID(),'暂停扮演'),/QUEUE_FULL/);assert.equal(s.store.controls().role,'paused');assert.equal(s.host.cancels.length,1);release();await s.coordinator.idle();assert.equal(s.store.history().filter(m=>m.role==='character').length,0);await close(s);});
test('已有业务提交后断连标未知，禁止盲重试；取消不抹掉提交结果',async()=>{const s=setup(),id=randomUUID();s.host.beforeResult=async()=>{const t=s.store.reauthorize(id,'SYNTHETIC 写入',true,s.store.controls().epoch);s.store.context(t.token,{});s.store.remember(t.token,'写入','arbitrary-operation-without-turn-prefix');};s.host.fail=true;s.coordinator.accept(s.store.scope,id,'SYNTHETIC 写入');await s.coordinator.idle();assert.equal(s.coordinator.snapshot().turns[0].status,'unknown_outcome');assert.equal(s.coordinator.snapshot().turns[0].side_effect_outcome,'committed');assert.throws(()=>s.coordinator.retryTurn(s.store.scope,id),/RECOVERY_NOT_ALLOWED/);await s.coordinator.cancelTurn(s.store.scope,id);assert.equal(s.coordinator.snapshot().turns[0].error_code,'CANCELLED_WITH_COMMITTED_OPERATIONS');assert.equal((s.store.db.prepare('select count(*) n from memories').get() as any).n,1);await close(s);});
test('确定失败保留off密文供有界显式重试，无自动重试',async()=>{const s=setup(false),id=randomUUID();s.host.fail=true;s.coordinator.accept(s.store.scope,id,'SYNTHETIC可重试');await s.coordinator.idle();assert.equal(s.host.calls,1);assert.equal(s.off.get(s.store.scope,id),'SYNTHETIC可重试');s.host.fail=false;s.coordinator.retryTurn(s.store.scope,id);await s.coordinator.idle();assert.equal(s.host.calls,2);assert.equal(s.coordinator.snapshot().turns[0].status,'completed');assert.equal((s.off.db.prepare('select count(*) n from receipts').get() as any).n,0);await close(s);});
test('独立control通路在队列满时成功、零普通容量；关闭记忆/撤回/暂停/取消有效',async()=>{const s=setup();let release!:()=>void;const gate=new Promise<void>(r=>release=r);s.host.beforeResult=()=>gate;s.coordinator.accept(s.store.scope,randomUUID(),'SYNTHETIC运行');for(let i=0;i<20;i++)s.coordinator.accept(s.store.scope,randomUUID(),'SYNTHETIC队列'+i);const count=s.coordinator.snapshot().turns.length;const c=s.coordinator.control(s.store.scope,{memory:'off',nicknameState:'suspended',role:'paused'});assert.equal(c.control_applied,true);assert.equal(c.controls.memory,'off');assert.equal(c.controls.nicknameState,'suspended');assert.equal(c.controls.role,'paused');assert.equal(s.coordinator.snapshot().turns.length,count);assert.equal(s.host.cancels.length,1);for(const t of s.coordinator.snapshot().turns.filter(t=>t.status==='queued'))await s.coordinator.cancelTurn(s.store.scope,t.turn_id);release();await s.coordinator.idle();assert.equal(s.host.calls,1);await close(s);});
test('取消已生成但未ack输出会撤回pending，重启不复活',async()=>{const s=setup(),id=randomUUID();s.coordinator.accept(s.store.scope,id,'SYNTHETIC pending');await s.coordinator.idle();const message=s.coordinator.snapshot().turns[0].message_id!;await s.coordinator.cancelTurn(s.store.scope,id);assert.equal(s.coordinator.snapshot().turns[0].status,'cancelled');assert.ok(!s.store.history().some(m=>m.id===message));assert.throws(()=>s.coordinator.ack(s.store.scope,id,message),/NOT_AUTHORIZED/);const file=s.store.file;await close(s);const next=new Store(file),c=new TurnCoordinator(next,new SyntheticHost(next));assert.equal(c.snapshot().turns[0].status,'cancelled');assert.ok(!next.history().some(m=>m.id===message));await c.close();next.close();});
test('context不读取未来排队输入或未ack的角色草稿',()=>{for(const memory of [true,false]){const s=setup(memory);const first=s.store.receive('first','SYNTHETIC first')!,second=s.store.receive('second','SYNTHETIC future')!;const initial=s.store.context(first.token,{});assert.ok(!initial.history.some(m=>m.text.includes('future')));const draft=s.store.prepare(first,'SYNTHETIC unconfirmed');const context=s.store.context(second.token,{});assert.ok(!context.history.some(m=>m.id===draft.id));s.off.close();s.store.close();}});
test('排队B的context包含稍后才确认的A回复，仍排除未来C',()=>{for(const memory of [true,false]){const s=setup(memory);const a=s.store.receive('a','SYNTHETIC A')!,b=s.store.receive('b','SYNTHETIC B')!;s.store.receive('c','SYNTHETIC C');s.store.context(a.token,{});const reply=s.store.prepare(a,'SYNTHETIC A confirmed reply');s.store.ack(reply.id);const context=s.store.context(b.token,{});assert.deepEqual(context.history.map(m=>m.text),['SYNTHETIC A','SYNTHETIC A confirmed reply','SYNTHETIC B']);s.off.close();s.store.close();}});

test('新协调器禁止没有read_context的合成宿主输出',async()=>{const s=setup();s.host.noContext=true;s.coordinator.accept(s.store.scope,randomUUID(),'SYNTHETIC no context');await s.coordinator.idle();assert.equal(s.coordinator.snapshot().turns[0].error_code,'CONTEXT_REQUIRED');assert.equal(s.store.history().filter(m=>m.role==='character').length,0);await close(s);});
test('观测离线/队列满/同步异常不降低业务结果且独立缺口可读',async()=>{for(const outcome of ['accepted','dropped','throw'] as const){const dir=mkdtempSync(path.join(os.tmpdir(),'observation-gap-')),store=new Store(path.join(dir,'state.db'));store.start(true,true,true);const host=new SyntheticHost(store);let emitted=0;const c=new TurnCoordinator(store,host,undefined,undefined,()=>Date.now(),{emit(){emitted++;if(outcome==='throw')throw Error('SYNTHETIC exporter offline');return outcome;}});try{c.accept(store.scope,randomUUID(),'SYNTHETIC observation independence');await c.idle();assert.equal(c.snapshot().turns[0].status,'completed');const gap=store.db.prepare('SELECT * FROM observation_gaps').get() as any;assert.equal(gap.dropped,outcome==='accepted'?0:emitted);assert.equal(gap.status,outcome==='accepted'?'accepted':'incomplete');assert.equal(host.calls,1);}finally{await c.close();store.close();}}});
test('运行中off输入过期删除密文并进入可取消恢复屏障',async()=>{let now=1000;const dir=mkdtempSync(path.join(os.tmpdir(),'off-expiry-')),store=new Store(path.join(dir,'state.db'),()=>now);store.start(true,true,false);const key=Buffer.alloc(32,3),off=new OffCache(path.join(dir,'spool.db'),key,store.authority,()=>now),host=new SyntheticHost(store),c=new TurnCoordinator(store,host,off,key,()=>now);try{host.fail=true;const id=randomUUID();c.accept(store.scope,id,'SYNTHETIC expiry');await c.idle();now+=900001;assert.throws(()=>off.get(store.scope,id),/OFF_INPUT_UNAVAILABLE/);assert.equal((off.db.prepare('SELECT count(*) n FROM receipts').get() as any).n,0);assert.throws(()=>c.retryTurn(store.scope,id),/RECOVERY_NOT_ALLOWED/);assert.equal(c.snapshot().turns[0].error_code,'OFF_INPUT_UNAVAILABLE');assert.throws(()=>c.accept(store.scope,randomUUID(),'SYNTHETIC after expiry'),/RECOVERY_REQUIRES_USER/);await c.cancelTurn(store.scope,id);host.fail=false;c.accept(store.scope,randomUUID(),'SYNTHETIC restored');await c.idle();assert.equal(c.snapshot().turns.at(-1)?.status,'completed');}finally{await c.close();off.close();store.close();}});
test('观测sink既拿不到角色正文，也不能修改主事件影响业务',async()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'observer-isolation-')),store=new Store(path.join(dir,'state.db'));store.start(true,true,true);const host=new SyntheticHost(store);const c=new TurnCoordinator(store,host,undefined,undefined,()=>Date.now(),{emit(event){assert.ok(!JSON.stringify(event).includes('测试替身回复'));(event as any).text='CORRUPTED';throw Error('SYNTHETIC failure');}});try{c.accept(store.scope,randomUUID(),'SYNTHETIC secret input');await c.idle();assert.equal(c.snapshot().turns[0].status,'completed');assert.equal(store.history().at(-1)?.text,'SYNTHETIC 测试替身回复，不是模型结果。');}finally{await c.close();store.close();}});
test('memory-off过期pending同时从瞬时history移除，不会反复显示ack失败',()=>{let now=1000;const store=new Store(path.join(mkdtempSync(path.join(os.tmpdir(),'pending-expire-')),'state.db'),()=>now);try{store.start(true,true,false);const t=store.receive('pending','SYNTHETIC')!;store.context(t.token,{});const reply=store.prepare(t,'SYNTHETIC pending reply');now+=600001;assert.ok(!store.history().some(m=>m.id===reply.id));assert.equal((store.db.prepare('SELECT count(*) n FROM pending').get() as any).n,0);}finally{store.close();}});
test('重启running的off输入丢失也建立独立屏障',async()=>{let now=1000;const dir=mkdtempSync(path.join(os.tmpdir(),'off-running-restart-')),file=path.join(dir,'state.db'),spool=path.join(dir,'spool.db'),key=Buffer.alloc(32,9),id=randomUUID();let store=new Store(file,()=>now);store.start(true,true,false);let off=new OffCache(spool,key,store.authority,()=>now),host=new SyntheticHost(store);host.fail=true;let c=new TurnCoordinator(store,host,off,key,()=>now);c.accept(store.scope,id,'SYNTHETIC crash');await c.idle();store.db.prepare("UPDATE runtime_turns SET status='running',error_code=NULL WHERE turn_id=?").run(id);await c.close();off.close();store.close();now+=900001;store=new Store(file,()=>now);off=new OffCache(spool,key,store.authority,()=>now);host=new SyntheticHost(store);c=new TurnCoordinator(store,host,off,key,()=>now);try{assert.equal(c.snapshot().turns[0].error_code,'OFF_INPUT_UNAVAILABLE');assert.throws(()=>c.accept(store.scope,randomUUID(),'SYNTHETIC next'),/RECOVERY_REQUIRES_USER/);assert.equal((store.db.prepare('SELECT input_lost FROM runtime_turns').get() as any).input_lost,1);}finally{await c.close();off.close();store.close();}});
test('在途过期后宿主失败不覆盖输入丢失；取消别项不误清屏障',async()=>{let now=1000;const dir=mkdtempSync(path.join(os.tmpdir(),'off-expiry-race-')),store=new Store(path.join(dir,'state.db'),()=>now);store.start(true,true,false);const key=Buffer.alloc(32,9),off=new OffCache(path.join(dir,'spool.db'),key,store.authority,()=>now),host=new SyntheticHost(store);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);host.beforeResult=()=>gate;host.fail=true;const c=new TurnCoordinator(store,host,off,key,()=>now),a=randomUUID(),b=randomUUID();try{c.accept(store.scope,a,'SYNTHETIC active');c.accept(store.scope,b,'SYNTHETIC queued');await new Promise(r=>setImmediate(r));now+=900001;off.expire();release();await c.idle();assert.equal(c.snapshot().turns.find(t=>t.turn_id===a)?.error_code,'OFF_INPUT_UNAVAILABLE');await c.cancelTurn(store.scope,b);assert.throws(()=>c.accept(store.scope,randomUUID(),'SYNTHETIC next'),/RECOVERY_REQUIRES_USER/);await c.cancelTurn(store.scope,a);assert.equal((store.db.prepare('SELECT control_uncertain FROM scope_safety WHERE scope=?').get(store.scope) as any).control_uncertain,0);}finally{release();await c.close();off.close();store.close();}});
