import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {readFileSync} from 'node:fs';import path from 'node:path';
import {Client} from '@modelcontextprotocol/client';import {StdioClientTransport} from '@modelcontextprotocol/client/stdio';
import type {Store,Turn} from '@between/core/store';import {fixture} from './memory-fixtures.js';
async function attached(store:Store,turn:Turn){const character=readFileSync('characters/alan.json','utf8'),transport=new StdioClientTransport({command:process.execPath,args:[path.resolve('packages/mcp-server/dist/trusted-stdio.js')],env:{PATH:process.env.PATH||'',REL_DB:store.file,REL_CHARACTER_JSON:character,REL_CHARACTER_SHA256:createHash('sha256').update(character).digest('hex'),REL_GRANT:turn.token,REL_SCOPE:store.scope},stderr:'pipe'}),client=new Client({name:'schema6-memory-test',version:'1'});await client.connect(transport);return client;}
const value=(r:any)=>JSON.parse(r.content[0].text);
test('actual MCP keeps two tools and validates all generic memory modes without scope/consent or semantic-projection authority',async()=>{
 // Stdio uses wall-clock grant expiry, so this synthetic fixture must use a
 // compatible current timestamp rather than its deterministic test clock.
 const f=fixture();f.advance(Date.now()-f.now());let first:Client|undefined,second:Client|undefined,third:Client|undefined;
 try{const t=f.turn('请记住：我每周三参加陶艺课');first=await attached(f.store,t);const list=await first.listTools();assert.deepEqual(list.tools.map(x=>x.name).sort(),['read_context','remember_user_report']);
 const request={mode:'standing',quote:t.text,expected_version:f.store.version(),operation_id:'standing'};let r:any=await first.callTool({name:'remember_user_report',arguments:request});assert.equal(r.isError,true);assert.match(JSON.stringify(r),/CONTEXT_REQUIRED/);
 let c:any=await first.callTool({name:'read_context',arguments:{}});assert.equal(value(c).memory_selection.state_version,0);r=await first.callTool({name:'remember_user_report',arguments:request});assert.equal(r.isError,undefined);const saved=value(r);assert.equal(saved.result.record_kind,'resident_quote');assert.equal(saved.committed,true);
 for(const invalid of [{...request,mode:'unknown'},{...request,scope:'other'},{...request,projection:{object:'MODEL_INVENTED'}},{...request,mode:'quote',expected_version:0},{...request,mode:'propose',proposed_kind:'hypothesis'}]){r=await first.callTool({name:'remember_user_report',arguments:invalid});assert.equal(r.isError,true);}
 const quote='更正记忆：「'+t.text+'」为「我每周五参加陶艺课」',u=f.turn(quote);second=await attached(f.store,u);await second.callTool({name:'read_context',arguments:{}});const revise={mode:'revise',quote,replacement_quote:'我每周五参加陶艺课',target_id:saved.result.id,target_revision:1,revision_mode:'correction',expected_version:f.store.version(),operation_id:'correction'};r=await second.callTool({name:'remember_user_report',arguments:revise});assert.equal(r.isError,undefined);const correction=value(r);assert.equal(correction.result.supersedes,saved.result.id);r=await second.callTool({name:'remember_user_report',arguments:revise});assert.deepEqual(value(r),correction);r=await second.callTool({name:'remember_user_report',arguments:{...revise,replacement_quote:'changed'}});assert.equal(r.isError,true);assert.match(JSON.stringify(r),/OPERATION_CONFLICT/);
 const p=f.turn('也许这个周末我会去徒步');third=await attached(f.store,p);await third.callTool({name:'read_context',arguments:{}});r=await third.callTool({name:'remember_user_report',arguments:{mode:'propose',quote:p.text,proposed_kind:'history',expected_version:f.store.version(),operation_id:'pending-proposal'}});assert.equal(r.isError,undefined);assert.equal(value(r).result.status,'needs_review');c=await third.callTool({name:'read_context',arguments:{}});assert.ok(!value(c).memories.some((m:any)=>m.id===value(r).result.id));assert.ok(f.store.history().some(m=>m.text===t.text));assert.ok(!value(c).history.some((m:any)=>m.text===t.text));
 f.store.set({memory:'off'});r=await third.callTool({name:'remember_user_report',arguments:{quote:p.text,operation_id:'late'}});assert.equal(r.isError,true);assert.match(JSON.stringify(r),/NOT_AUTHORIZED/);
 }finally{await third?.close();await second?.close();await first?.close();f.store.close();}
});
