import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import path from 'node:path';import {Store} from '@between/core/store';
import {BackupManager,verifySchema} from '@between/core/privacy/backup';
import {OfflineRecovery} from '@between/core/privacy/offline-recovery';
import {sanitizeRestoredImage} from '@between/core/privacy/restore-policy';
import {fixture} from './memory-fixtures.js';

test('schema6 fresh metadata is checked and schema5 is refused read-only without migration',()=>{
 const f=fixture();try{f.save('我每周参加陶艺课');assert.equal(f.store.db.pragma('user_version',{simple:true}),6);assert.doesNotThrow(()=>verifySchema(f.store.db));f.store.db.pragma('user_version=5');f.store.close();const before=readFileSync(f.file);assert.throws(()=>new Store(f.file,f.now,true,'synthetic-memory'),/UNSUPPORTED_DATABASE_SCHEMA/);assert.deepEqual(readFileSync(f.file),before);}finally{f.store.close();}
});
test('schema6 label with a missing critical metadata column fails preflight before writable open',()=>{
 const f=fixture();try{f.store.db.exec('ALTER TABLE sources RENAME COLUMN revision TO old_revision');f.store.close();const before=readFileSync(f.file);assert.throws(()=>new Store(f.file,f.now,true,'synthetic-memory'),/UNSUPPORTED_DATABASE_SCHEMA/);assert.deepEqual(readFileSync(f.file),before);}finally{f.store.close();}
});
test('schema6 metadata participates in backup digest and verified encrypted restore staging',async()=>{
 const f=fixture();let manager:BackupManager|undefined;try{f.save('我每周参加陶艺课');manager=new BackupManager(f.store,path.join(path.dirname(f.file),'backups'),Buffer.alloc(32,41),f.now);const backup=await manager.create();assert.equal(manager.validateRestore(backup.id).validated,true);f.store.db.prepare('UPDATE memories SET valid_until=?').run(f.now()+10000);assert.throws(()=>manager!.validateRestore(backup.id),/BACKUP_STALE_BUSINESS_STATE/);}finally{manager?.close();f.store.close();}
});
test('actual offline schema6 restore preserves admitted quote, seals no off-interval input and never replays operations',async()=>{
 const f=fixture();let recovery:OfflineRecovery|undefined,next:Store|undefined;try{const saved=f.save('我每周参加陶艺课');f.store.set({memory:'off'});f.turn('OFF_SECRET_NOT_IN_RESTORED_MEMORY');f.store.set({memory:'on'});const operations=f.store.db.prepare('SELECT * FROM operations').all();f.store.close();recovery=new OfflineRecovery(f.file,path.join(path.dirname(f.file),'sealed'),Buffer.alloc(32,42),f.now);const seal=await recovery.createSealedCheckpoint();writeFileSync(f.file,'SYNTHETIC_CORRUPT_MAIN');const r=recovery.activateRestore({...seal,confirmation:'activate_sealed_checkpoint'});assert.equal(r.restoration_performed,true);assert.equal(r.execution_started,false);next=new Store(f.file,f.now,true,'synthetic-memory');assert.equal(next.db.pragma('user_version',{simple:true}),6);assert.deepEqual(next.db.prepare('SELECT * FROM operations').all(),operations);const t=next.receive('restored-query','继续聊我的活动')!,context=next.context(t.token,{});assert.ok(context.memories.some(m=>m.id===saved.id));assert.ok(!JSON.stringify(next.db.prepare('SELECT * FROM sources').all()).includes('OFF_SECRET'));}finally{next?.close();recovery?.close();f.store.close();}
});
test('restore-policy shares retention/minimal-evidence and unverified-proposal expiration rules',()=>{
 const f=fixture();try{const retained=f.save('我每周参加陶艺课'),negation=f.turn('以前我喜欢雨天，现在不喜欢');f.store.context(negation.token,{});const fragment=f.store.remember(negation.token,'我喜欢雨天','fragment');const p=f.turn('我猜自己可能有某种疾病');f.store.context(p.token,{});const proposal=f.store.rememberProposed(p.token,{quote:p.text,proposed_kind:'fact',expected_version:f.store.version(),operation_id:'proposal'});f.advance(30*86400000+1);sanitizeRestoredImage(f.store.db,f.store.authority.all(),f.now());const row=f.store.db.prepare('SELECT * FROM memories WHERE id=?').get(proposal.result.id) as any;assert.equal(row.status,'invalid');assert.equal(row.text,'');assert.equal(row.evidence_text,'');assert.equal((f.store.db.prepare('SELECT revision FROM sources WHERE id=?').get(retained.turn.source) as any).revision,1);assert.equal((f.store.db.prepare('SELECT status FROM memories WHERE id=?').get(fragment.result.id) as any).status,'invalid');assert.ok(f.store.search('陶艺').some(m=>m.id===retained.id));assert.ok(!f.store.search('雨天').some(m=>m.id===fragment.result.id));}finally{f.store.close();}
});
test('deletion preview suppresses all new memory metadata and current grants; committed deletion clears every controlled row',()=>{
 const f=fixture();try{f.save('我每周参加陶艺课');const p=f.turn('可能有帮助的计划');f.store.context(p.token,{});f.store.rememberProposed(p.token,{quote:p.text,proposed_kind:'history',expected_version:f.store.version(),operation_id:'proposal'});const plan=f.store.planDeletion(f.store.scope);assert.deepEqual(f.store.search('陶艺'),[]);assert.throws(()=>f.store.context(p.token,{}),/RELATIONSHIP_SUPPRESSED/);f.store.confirmDeletion(f.store.scope,plan.plan_id,plan.digest,plan.confirmation_token);f.store.clearRelationshipRecords();f.store.verifyRelationshipErased();for(const table of ['memories','sources','memory_fts','operations'])assert.equal((f.store.db.prepare(`SELECT count(*) n FROM ${table}`).get() as any).n,0);}finally{f.store.close();}
});

test('idle open owner maintenance clears expired proposal bodies without incoming input or history reads',async()=>{
 const f=fixture();try{const t=f.turn('暂时还不确定的计划');f.store.context(t.token,{});const p=f.store.rememberProposed(t.token,{quote:t.text,proposed_kind:'history',expected_version:0,operation_id:'idle-proposal'});f.advance(4*3600000);await new Promise(resolve=>setTimeout(resolve,1150));const row=f.store.db.prepare('SELECT * FROM memories WHERE id=?').get(p.result.id) as any;assert.equal(row.status,'invalid');assert.equal(row.text,'');assert.equal(row.evidence_text,'');assert.equal((f.store.db.prepare('SELECT count(*) n FROM memory_fts WHERE id=?').get(p.result.id) as any).n,0);}finally{f.store.close();}
});
test('new encrypted backup synchronously removes expired proposals even before the idle maintenance tick',async()=>{
 const f=fixture();let manager:BackupManager|undefined;try{const t=f.turn('临时计划');f.store.context(t.token,{});const p=f.store.rememberProposed(t.token,{quote:t.text,proposed_kind:'history',expected_version:0,operation_id:'backup-proposal'});f.advance(4*3600000);manager=new BackupManager(f.store,path.join(path.dirname(f.file),'backups'),Buffer.alloc(32,43),f.now);const backup=await manager.create();assert.equal((f.store.db.prepare('SELECT text FROM memories WHERE id=?').get(p.result.id) as any).text,'');assert.equal(manager.validateRestore(backup.id).validated,true);}finally{manager?.close();f.store.close();}
});

test('offline checkpoint refuses newly archiving expired pending bodies without changing main or seal; normal startup cleanup unblocks it',async()=>{
 const f=fixture();let recovery:OfflineRecovery|undefined;try{const t=f.turn('未确认的临时计划');f.store.context(t.token,{});const p=f.store.rememberProposed(t.token,{quote:t.text,proposed_kind:'history',expected_version:0,operation_id:'offline-pending'});f.store.close();recovery=new OfflineRecovery(f.file,path.join(path.dirname(f.file),'sealed'),Buffer.alloc(32,44),f.now);await recovery.createSealedCheckpoint();const sealBefore=recovery.authority.getSeal(),mainBefore=readFileSync(f.file);f.advance(4*3600000);await assert.rejects(()=>recovery!.createSealedCheckpoint(),/RECOVERY_EXPIRED_PENDING_MEMORY/);assert.deepEqual(readFileSync(f.file),mainBefore);assert.deepEqual(recovery.authority.getSeal(),sealBefore);assert.equal(recovery.recoverInterruptedActivation().recovered,true);assert.deepEqual(recovery.authority.getSeal(),sealBefore);f.reopen();assert.equal((f.store.db.prepare('SELECT text FROM memories WHERE id=?').get(p.result.id) as any).text,'');f.store.close();const next=await recovery.createSealedCheckpoint();assert.equal(recovery.inspectRestore(next.id).eligible,true);}finally{f.store.close();recovery?.close();}
});
test('restore minimization never reconstructs invalid or older-revision source evidence',()=>{
 const f=fixture();try{const a=f.save('旧错误断言'),b=f.save('编辑前的断言');f.store.db.prepare('UPDATE sources SET valid=0 WHERE id=?').run(a.turn.source);f.store.db.prepare("UPDATE sources SET text='编辑后的真实输入',revision=revision+1 WHERE id=?").run(b.turn.source);f.advance(30*86400000+1);sanitizeRestoredImage(f.store.db,f.store.authority.all(),f.now());for(const id of [a.id,b.id]){const m=f.store.db.prepare('SELECT * FROM memories WHERE id=?').get(id) as any;assert.equal(m.status,'invalid');assert.equal(m.text,'');assert.equal(m.evidence_text,'');}assert.ok(!JSON.stringify(f.store.db.prepare('SELECT text FROM sources').all()).includes('旧错误'));assert.ok(!JSON.stringify(f.store.db.prepare('SELECT text FROM sources').all()).includes('编辑前'));assert.deepEqual(f.store.search('断言'),[]);}finally{f.store.close();}
});

test('source invalidation after prior thirty-day minimization clears the retained derived source copy too',()=>{
 const f=fixture();try{const saved=f.save('保留证据随后被撤回');f.advance(30*86400000+1);f.store.purge();assert.equal((f.store.db.prepare('SELECT evidence_only FROM sources WHERE id=?').get(saved.turn.source) as any).evidence_only,1);f.store.db.prepare('UPDATE sources SET valid=0 WHERE id=?').run(saved.turn.source);f.store.purge();assert.equal((f.store.db.prepare('SELECT text FROM sources WHERE id=?').get(saved.turn.source) as any).text,'');assert.equal((f.store.db.prepare('SELECT text FROM memories WHERE id=?').get(saved.id) as any).text,'');f.reopen();assert.deepEqual(f.store.search('证据'),[]);}finally{f.store.close();}
});
