import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,writeFileSync} from 'node:fs';import path from 'node:path';import {createDecipheriv} from 'node:crypto';import Database from 'better-sqlite3';
import {Store} from '@between/core/store';import {BackupManager} from '@between/core/privacy/backup';import {fixture} from './memory-fixtures.js';

test('whole-database backup clears expired candidates in every active scoped authority it actually archives',async()=>{
 const f=fixture();let other:Store|undefined,manager:BackupManager|undefined,archive:Database.Database|undefined;try{
  other=new Store(f.file,f.now,false,'synthetic-other');other.start(true,true,true);const quote=other.receive('whole-history','完整且合法的另一作用域历史')!;other.context(quote.token,{});const kept=other.remember(quote.token,quote.text,'retained-history');const t=other.receive('pending','SYNTHETIC_OTHER_SCOPE_PENDING')!;other.context(t.token,{});const pending=other.rememberProposed(t.token,{quote:t.text,proposed_kind:'history',expected_version:other.version(),operation_id:'pending-candidate'});f.advance(4*3600000+1);
  const key=Buffer.alloc(32,77);manager=new BackupManager(f.store,path.join(path.dirname(f.file),'backups'),key,f.now);const created=await manager.create();
  // Inspect the actual synthetic encrypted archive, not just the source store.
  const bytes=readFileSync(path.join(manager.directory,created.id+'.relbackup')),magic=Buffer.from('REL_BACKUP_V1\0'),decipher=createDecipheriv('aes-256-gcm',key,bytes.subarray(magic.length,magic.length+12));decipher.setAAD(magic);decipher.setAuthTag(bytes.subarray(magic.length+12,magic.length+28));const payload=JSON.parse(Buffer.concat([decipher.update(bytes.subarray(magic.length+28)),decipher.final()]).toString('utf8')),file=path.join(path.dirname(f.file),'inspected-archive.sqlite');writeFileSync(file,Buffer.from(payload.database,'base64'),{mode:0o600});archive=new Database(file,{readonly:true,fileMustExist:true});
  assert.ok(payload.authority.some((s:any)=>s.scope==='synthetic-other'));assert.equal((archive.prepare('SELECT text FROM memories WHERE id=?').get(kept.result.id) as any).text,quote.text,'the archive intentionally covers the other active scope');
  for(const db of [archive,other.db]){const row=db.prepare('SELECT * FROM memories WHERE id=?').get(pending.result.id) as any;assert.equal(row.status,'invalid');assert.equal(row.text,'');assert.equal(row.evidence_text,'');assert.equal((db.prepare('SELECT count(*) n FROM memory_fts WHERE id=?').get(pending.result.id) as any).n,0);}
 }finally{archive?.close();manager?.close();other?.close();f.store.close();}
});

test('preview, cleaning and deleted covered authorities reject backup before changing any scoped inventory',async()=>{
 for(const state of ['preview','cleaning','deleted']){const f=fixture();let other:Store|undefined,manager:BackupManager|undefined;try{const a=f.turn('OWNER_PENDING');f.store.context(a.token,{});f.store.rememberProposed(a.token,{quote:a.text,proposed_kind:'history',expected_version:0,operation_id:'owner-pending'});other=new Store(f.file,f.now,false,'synthetic-other');other.start(true,true,true);const t=other.receive('pending','SYNTHETIC_PENDING_UNDER_PREVIEW')!;other.context(t.token,{});other.rememberProposed(t.token,{quote:t.text,proposed_kind:'history',expected_version:0,operation_id:'pending'});f.advance(4*3600000+1);other.authority.db.prepare('UPDATE scopes SET state=? WHERE scope=?').run(state,other.scope);manager=new BackupManager(f.store,path.join(path.dirname(f.file),'backups'),Buffer.alloc(32,78),f.now);const before=other.db.prepare('SELECT * FROM memories ORDER BY scope,id').all();await assert.rejects(()=>manager!.create(),/BACKUP_CURRENT_AUTHORITY_REQUIRED/);assert.deepEqual(other.db.prepare('SELECT * FROM memories ORDER BY scope,id').all(),before);assert.equal(manager.status().length,0);}finally{manager?.close();other?.close();f.store.close();}}
});
test('extra or missing scope membership and unattributed rows reject backup before owner cleanup',async()=>{
 for(const damage of ['extra','missing','unattributed']){const f=fixture();let other:Store|undefined,manager:BackupManager|undefined;try{const t=f.turn('OWNER_PENDING');f.store.context(t.token,{});const pending=f.store.rememberProposed(t.token,{quote:t.text,proposed_kind:'history',expected_version:0,operation_id:'owner-pending'});other=new Store(f.file,f.now,false,'synthetic-other');other.start(true,true,true);f.advance(4*3600000+1);if(damage==='extra')f.store.db.prepare('INSERT INTO privacy_versions VALUES(?,0)').run('unregistered');if(damage==='missing')f.store.db.prepare('DELETE FROM privacy_versions WHERE scope=?').run(other.scope);if(damage==='unattributed')f.store.db.prepare('INSERT INTO messages(id,role,text,status,at,scope) VALUES(?,?,?,?,?,?)').run('unattributed','user','UNATTRIBUTED_BODY','confirmed',f.now(),'unregistered');manager=new BackupManager(f.store,path.join(path.dirname(f.file),'backups'),Buffer.alloc(32,79),f.now);const before=f.store.db.prepare('SELECT * FROM memories WHERE id=?').get(pending.result.id);await assert.rejects(()=>manager!.create(),/BACKUP_CURRENT_AUTHORITY_REQUIRED|RESTORE_SCOPE_VECTOR_MISMATCH|RESTORE_UNATTRIBUTED_RECORDS/);assert.deepEqual(f.store.db.prepare('SELECT * FROM memories WHERE id=?').get(pending.result.id),before);assert.equal(manager.status().length,0);}finally{manager?.close();other?.close();f.store.close();}}
});
test('the installation owner timer retires idle attached-scope candidates while preserving every inactive inventory',async()=>{
 const f=fixture();const attached:Store[]=[];try{const rows:{store:Store;id:string;before:unknown}[]=[];for(const state of ['active','preview','cleaning','deleted']){const s=new Store(f.file,f.now,false,'scope-'+state);attached.push(s);s.start(true,true,true);const t=s.receive('pending','PENDING_'+state)!;s.context(t.token,{});const p=s.rememberProposed(t.token,{quote:t.text,proposed_kind:'history',expected_version:0,operation_id:'candidate'});if(state!=='active')s.authority.db.prepare('UPDATE scopes SET state=? WHERE scope=?').run(state,s.scope);rows.push({store:s,id:p.result.id,before:s.db.prepare('SELECT * FROM memories WHERE id=?').get(p.result.id)});}f.advance(4*3600000+1);await new Promise(resolve=>setTimeout(resolve,1150));for(const row of rows){const current=row.store.db.prepare('SELECT * FROM memories WHERE id=?').get(row.id) as any;if(row.store.scope==='scope-active'){assert.equal(current.status,'invalid');assert.equal(current.text,'');assert.equal((row.store.db.prepare('SELECT count(*) n FROM memory_fts WHERE id=?').get(row.id) as any).n,0);}else assert.deepEqual(current,row.before);}}finally{for(const s of attached)s.close();f.store.close();}
});
