import test from 'node:test';import assert from 'node:assert/strict';import {fixture} from './memory-fixtures.js';
import type {ReviseMemoryInput} from '@between/core/store';
function revision(f:ReturnType<typeof fixture>,target:{id:string;text:string;revision?:number},replacement='我喜欢晴天',mode:'correction'|'change'='correction'){
 const quote=(mode==='correction'?'更正记忆':'更新记忆')+'：「'+target.text+'」为「'+replacement+'」',turn=f.turn(quote);f.store.context(turn.token,{});const input:ReviseMemoryInput={target_id:target.id,target_revision:target.revision??1,mode,quote,replacement_quote:replacement,expected_version:f.store.version(),operation_id:'revise-'+turn.id};return {turn,input};
}
test('generic explicit correction atomically clears target/body/index and returns idempotent historical receipt',()=>{
 const f=fixture();try{const old=f.save(),r=revision(f,{id:old.id,text:old.turn.text});const applied=f.store.reviseMemory(r.turn.token,r.input),version=f.store.version();assert.equal(applied.result.supersedes,old.id);assert.equal(applied.readback_memory?.status,'active');const target=f.store.db.prepare('SELECT * FROM memories WHERE id=?').get(old.id) as any;assert.equal(target.status,'invalid');assert.equal(target.revision,2);assert.equal(target.text,'');assert.equal(target.evidence_text,'');assert.equal((f.store.db.prepare('SELECT count(*) n FROM memory_fts WHERE id=?').get(old.id) as any).n,0);assert.equal((f.store.db.prepare('SELECT text,evidence_only FROM sources WHERE id=?').get(old.turn.source) as any).text,'');assert.ok(f.store.history().some(m=>m.text===old.turn.text));assert.ok(!f.store.context(r.turn.token,{}).history.some(m=>m.text===old.turn.text));assert.deepEqual(f.store.reviseMemory(r.turn.token,r.input),applied);assert.equal(f.store.version(),version);assert.throws(()=>f.store.reviseMemory(r.turn.token,{...r.input,replacement_quote:'changed'}),/OPERATION_CONFLICT/);assert.throws(()=>f.store.reviseMemory(r.turn.token,{...r.input,target_revision:2}),/OPERATION_CONFLICT/);assert.ok(f.store.search('晴天').some(m=>m.id===applied.result.id));}finally{f.store.close();}
});
test('change expires exact target without erasing true prior quotation and never reactivates on duplicate receipt',()=>{
 const f=fixture();try{const old=f.save(),r=revision(f,{id:old.id,text:old.turn.text},'现在我更喜欢下雪','change'),applied=f.store.reviseMemory(r.turn.token,r.input);const row=f.store.db.prepare('SELECT * FROM memories WHERE id=?').get(old.id) as any;assert.equal(row.status,'superseded');assert.equal(row.valid_until,f.now());assert.equal(row.text,old.turn.text);assert.ok(!f.store.search('雨天').some(m=>m.id===old.id));const newer=revision(f,{id:applied.result.id,text:'现在我更喜欢下雪'},'现在我偏爱清晨散步','change');f.store.reviseMemory(newer.turn.token,newer.input);const retry=f.store.reviseMemory(r.turn.token,r.input);assert.deepEqual(retry.result,applied.result);assert.equal(retry.readback_memory?.status,'superseded');assert.equal(retry.readback_memory?.revision,2);assert.equal((f.store.db.prepare('SELECT count(*) n FROM memories').get() as any).n,3);}finally{f.store.close();}
});
test('unsupported semantic reinterpretation or changed target does not alter any old record',()=>{
 const f=fixture();try{const rain=f.save(),sun=f.save('我喜欢晴天'),t=f.turn('更正：我喜欢晴天');f.store.context(t.token,{});const before=f.store.version();assert.throws(()=>f.store.reviseMemory(t.token,{target_id:rain.id,target_revision:1,mode:'correction',quote:t.text,replacement_quote:'我喜欢晴天',expected_version:before,operation_id:'ambiguous'}),/UNSUPPORTED_MEMORY_SEMANTICS/);assert.equal(f.store.version(),before);assert.equal((f.store.db.prepare("SELECT count(*) n FROM memories WHERE status='active'").get() as any).n,2);const explicit=revision(f,{id:rain.id,text:rain.turn.text});assert.throws(()=>f.store.reviseMemory(explicit.turn.token,{...explicit.input,target_id:sun.id}),/UNSUPPORTED_MEMORY_SEMANTICS/);}finally{f.store.close();}
});
test('CAS and forced transaction rollback leave target, replacement, index and operation receipt unchanged',()=>{
 const f=fixture();try{const old=f.save(),r=revision(f,{id:old.id,text:old.turn.text}),before=f.store.version();assert.throws(()=>f.store.reviseMemory(r.turn.token,{...r.input,target_revision:8}),/STALE_REVISION/);assert.throws(()=>f.store.reviseMemory(r.turn.token,{...r.input,expected_version:before+1}),/STALE_REVISION/);f.store.db.exec("CREATE TEMP TRIGGER block_memory BEFORE INSERT ON memories BEGIN SELECT RAISE(ABORT,'synthetic rollback'); END");assert.throws(()=>f.store.reviseMemory(r.turn.token,r.input),/synthetic rollback/);assert.equal(f.store.version(),before);assert.equal((f.store.db.prepare('SELECT status FROM memories WHERE id=?').get(old.id) as any).status,'active');assert.equal((f.store.db.prepare('SELECT count(*) n FROM memory_fts WHERE id=?').get(old.id) as any).n,1);assert.equal((f.store.db.prepare('SELECT count(*) n FROM operations WHERE id=?').get(r.input.operation_id) as any).n,0);f.store.db.exec('DROP TRIGGER block_memory');assert.equal(f.store.reviseMemory(r.turn.token,r.input).readback_memory?.status,'active');}finally{f.store.close();}
});
test('current source validity, grant/read-context, revision and epoch are checked before cached receipt',()=>{
 const f=fixture();try{const old=f.save(),r=revision(f,{id:old.id,text:old.turn.text});f.store.reviseMemory(r.turn.token,r.input);f.store.db.prepare('UPDATE sources SET valid=0 WHERE id=?').run(r.turn.source);assert.throws(()=>f.store.reviseMemory(r.turn.token,r.input),/INVALID_SOURCE/);f.store.db.prepare('UPDATE sources SET valid=1,revision=revision+1 WHERE id=?').run(r.turn.source);assert.throws(()=>f.store.reviseMemory(r.turn.token,r.input),/INVALID_SOURCE/);f.store.db.prepare('UPDATE sources SET revision=revision-1 WHERE id=?').run(r.turn.source);f.store.db.prepare('UPDATE grants SET read_context=0 WHERE source=?').run(r.turn.source);assert.throws(()=>f.store.reviseMemory(r.turn.token,r.input),/CONTEXT_REQUIRED/);f.store.db.prepare('UPDATE grants SET read_context=1 WHERE source=?').run(r.turn.source);f.store.set({memory:'off'});f.store.set({memory:'on'});assert.throws(()=>f.store.reviseMemory(r.turn.token,r.input),/NOT_AUTHORIZED/);}finally{f.store.close();}
});
test('late extraction from sealed old source cannot restore old value with a fresh operation ID',()=>{
 const f=fixture();try{const old=f.save(),r=revision(f,{id:old.id,text:old.turn.text});f.store.reviseMemory(r.turn.token,r.input);assert.throws(()=>f.store.rememberStanding(old.turn.token,{...old.input,expected_version:f.store.version(),operation_id:'new-late-operation'}),/INVALID_SOURCE/);assert.throws(()=>f.store.remember(old.turn.token,old.turn.text,'new-late-raw'),/INVALID_SOURCE/);const cached=f.store.rememberStanding(old.turn.token,old.input);assert.equal(cached.result.id,old.id);assert.equal((f.store.db.prepare('SELECT status FROM memories WHERE id=?').get(old.id) as any).status,'invalid');}finally{f.store.close();}
});
test('correction preserves unrelated candidate evidence until its own expiry, and purge never restores cleared text',()=>{
 const f=fixture();try{const old=f.save(),first=revision(f,{id:old.id,text:old.turn.text},'我喜欢登山');const unrelated=f.store.remember(first.turn.token,'更正记忆','unrelated-fragment');first.input.expected_version=f.store.version();const replacement=f.store.reviseMemory(first.turn.token,first.input);const second=revision(f,{id:replacement.result.id,text:'我喜欢登山'},'我喜欢徒步');f.store.reviseMemory(second.turn.token,second.input);assert.equal((f.store.db.prepare('SELECT text FROM memories WHERE id=?').get(unrelated.result.id) as any).text,'更正记忆');assert.equal((f.store.db.prepare('SELECT text FROM sources WHERE id=?').get(first.turn.source) as any).text,'更正记忆');f.advance(30*86400000+1);f.store.purge();assert.equal((f.store.db.prepare('SELECT text FROM sources WHERE id=?').get(first.turn.source) as any).text,'');f.reopen();assert.ok(!f.store.search('登山').some(m=>m.id===replacement.result.id));}finally{f.store.close();}
});


test('corrected long-memory evidence never carries the old body through current recall, thirty-day minimization or restore',()=>{
 const f=fixture();try{const old=f.save('WRONG_SYNTHETIC_OLD_VALUE'),r=revision(f,{id:old.id,text:old.turn.text},'CORRECT_SYNTHETIC_NEW_VALUE'),saved=f.store.reviseMemory(r.turn.token,r.input);const current=f.store.search('NEW_VALUE');assert.ok(current.some(m=>m.id===saved.result.id));assert.ok(!JSON.stringify(current).includes('WRONG_SYNTHETIC'));assert.throws(()=>f.store.remember(r.turn.token,'WRONG_SYNTHETIC_OLD_VALUE','late-wrong-fragment'),/INVALID_SOURCE/);const memory=f.store.db.prepare('SELECT * FROM memories WHERE id=?').get(saved.result.id) as any;assert.equal(memory.evidence_text,'CORRECT_SYNTHETIC_NEW_VALUE');assert.ok(!memory.admission_provenance.includes('WRONG_SYNTHETIC'));assert.equal(JSON.parse(memory.admission_provenance).kind,'correction');f.advance(30*86400000+1);f.store.purge();assert.equal((f.store.db.prepare('SELECT text FROM sources WHERE id=?').get(r.turn.source) as any).text,'CORRECT_SYNTHETIC_NEW_VALUE');assert.ok(!JSON.stringify(f.store.db.prepare("SELECT * FROM memories WHERE status='active'").all()).includes('WRONG_SYNTHETIC'));f.reopen();assert.ok(!JSON.stringify(f.store.search('NEW_VALUE')).includes('WRONG_SYNTHETIC'));}finally{f.store.close();}
});
test('change expires equivalent raw/standing representations whichever is targeted, while independent reports survive',()=>{
 for(const targetKind of ['raw','standing']){const f=fixture();try{const old=f.save('我喜欢看纸质书'),raw=f.store.remember(old.turn.token,old.turn.text,'also-raw'),independent=f.save('我喜欢听音乐');const r=revision(f,{id:targetKind==='raw'?raw.result.id:old.id,text:old.turn.text},'现在我喜欢看电子书','change');f.store.reviseMemory(r.turn.token,r.input);for(const id of [raw.result.id,old.id]){const row=f.store.db.prepare('SELECT * FROM memories WHERE id=?').get(id) as any;assert.equal(row.status,'superseded');assert.equal(row.valid_until,f.now());assert.equal(row.text,old.turn.text);}const results=f.store.search('纸质书');assert.ok(!results.some(m=>m.id===raw.result.id||m.id===old.id));assert.equal((f.store.db.prepare('SELECT status FROM memories WHERE id=?').get(independent.id) as any).status,'active');}finally{f.store.close();}}
});

test('quote-before-revise and proposed/partial-before-revise cannot preserve old text through retention or return it as current truth',()=>{
 for(const prior of ['quote','propose','partial','old-bearing-evidence'] as const){const f=fixture();try{const old=f.save('SYNTHETIC_WRONG_OLD'),r=revision(f,{id:old.id,text:old.turn.text},'SYNTHETIC_CORRECT_NEW');let priorId:string,priorReceipt:any,repeat:()=>any;
  if(prior==='propose'){const input={quote:r.turn.text,proposed_kind:'history' as const,expected_version:f.store.version(),operation_id:'prior-proposal'};priorReceipt=f.store.rememberProposed(r.turn.token,input);repeat=()=>f.store.rememberProposed(r.turn.token,input);}
  else {const quote=prior==='quote'?r.turn.text:prior==='partial'?'SYNTHETIC_WRONG_OLD':'SYNTHETIC_CORRECT_NEW';priorReceipt=f.store.remember(r.turn.token,quote,'prior-quote');repeat=()=>f.store.remember(r.turn.token,quote,'prior-quote');}
  priorId=priorReceipt.result.id;if(prior==='old-bearing-evidence')f.store.db.prepare('UPDATE memories SET evidence_text=? WHERE id=?').run(r.turn.text,priorId);
  const independent=f.store.remember(r.turn.token,'更正记忆','independent-prefix');r.input.expected_version=f.store.version();const result=f.store.reviseMemory(r.turn.token,r.input);const row=f.store.db.prepare('SELECT * FROM memories WHERE id=?').get(priorId) as any;assert.equal(row.status,'invalid');assert.equal(row.text,'');assert.equal(row.evidence_text,'');assert.equal((f.store.db.prepare('SELECT count(*) n FROM memory_fts WHERE id=?').get(priorId) as any).n,0);const receipt=repeat();assert.deepEqual(receipt.result,priorReceipt.result);assert.equal(receipt.readback_memory.status,'invalid');assert.equal((f.store.db.prepare('SELECT text FROM memories WHERE id=?').get(independent.result.id) as any).text,'更正记忆');assert.ok(f.store.history().some(m=>m.text===r.turn.text));assert.ok(!JSON.stringify(f.store.context(r.turn.token,{}).memories).includes('SYNTHETIC_WRONG_OLD'));
  f.advance(30*86400000+1);f.store.purge();assert.ok(!JSON.stringify(f.store.db.prepare('SELECT text FROM sources').all()).includes('SYNTHETIC_WRONG_OLD'));assert.ok(!JSON.stringify(f.store.db.prepare('SELECT text FROM memory_fts').all()).includes('SYNTHETIC_WRONG_OLD'));f.reopen();const next=f.turn('继续讨论');const context=f.store.context(next.token,{});assert.ok(context.memories.some(m=>m.id===result.result.id));assert.ok(!JSON.stringify(context).includes('SYNTHETIC_WRONG_OLD'));
 }finally{f.store.close();}}
});
