import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,writeFileSync,unlinkSync,readdirSync} from 'node:fs';
import os from 'node:os';import path from 'node:path';
import {Store} from '@between/core/store';
import {OfflineRecovery} from '@between/core/privacy/offline-recovery';
import {TurnCoordinator} from '@between/core/runtime/turn-coordinator';
import type {HostAdapter} from '@between/contracts/host';
const fixture=()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'sealed-recovery-')),file=path.join(dir,'main.sqlite'),directory=path.join(dir,'sealed'),key=Buffer.alloc(32,19),now=()=>100000;const store=new Store(file,now,true,'synthetic');store.start(true,true,true);store.set({memory:'on'});const turn=store.receive('input','SYNTHETIC_SEALED_CANARY')!;store.context(turn.token,{});store.remember(turn.token,'SYNTHETIC_SEALED_CANARY','committed');store.end(turn,turn.id,'completed');return {dir,file,directory,key,now,store};};
test('sealed checkpoint requires all live Store handles closed and archives no current authority',async()=>{const f=fixture(),recovery=new OfflineRecovery(f.file,f.directory,f.key,f.now);await assert.rejects(()=>recovery.createSealedCheckpoint(),/INSTALLATION_HANDLES_OPEN/);f.store.close();try{const seal=await recovery.createSealedCheckpoint();assert.equal(recovery.inspectRestore(seal.id).eligible,true);assert.equal(recovery.authority.maintenanceState().mode,'ready');assert.ok(!readFileSync(path.join(f.directory,seal.id+'.relcheckpoint')).includes(Buffer.from('SYNTHETIC_SEALED_CANARY')));assert.ok(!readdirSync(f.dir).some(name=>name.startsWith('.recovery-')));assert.deepEqual(seal.excludes,['receipt_spool','current_authority']);}finally{recovery.close();}});
test('successful normal read-write reopen consumes a seal before any subsequent activity',async()=>{const f=fixture();f.store.close();const recovery=new OfflineRecovery(f.file,f.directory,f.key,f.now);try{const seal=await recovery.createSealedCheckpoint(),store=new Store(f.file,f.now,true,'synthetic');store.close();assert.throws(()=>recovery.inspectRestore(seal.id),/RECOVERY_SEAL_REQUIRED/);}finally{recovery.close();}});
test('missing and corrupt read-only launch attempts preserve sealed recovery eligibility',async()=>{for(const missing of [false,true]){const f=fixture();f.store.close();const recovery=new OfflineRecovery(f.file,f.directory,f.key,f.now);try{const seal=await recovery.createSealedCheckpoint();if(missing)unlinkSync(f.file);else writeFileSync(f.file,'SYNTHETIC_CORRUPT_MAIN');assert.throws(()=>new Store(f.file,f.now,true,'synthetic'));assert.equal(recovery.inspectRestore(seal.id).eligible,true);assert.equal((recovery.authority.db.prepare('SELECT count(*) n FROM handles').get() as {n:number}).n,0);}finally{recovery.close();}}});
test('seal authentication and explicit seven-day expiry reject tampered and expired archives',async()=>{const f=fixture();f.store.close();let now=100000;const recovery=new OfflineRecovery(f.file,f.directory,f.key,()=>now);try{const seal=await recovery.createSealedCheckpoint(),file=path.join(f.directory,seal.id+'.relcheckpoint'),bytes=readFileSync(file);bytes[bytes.length-1]^=1;writeFileSync(file,bytes);assert.throws(()=>recovery.inspectRestore(seal.id),/RECOVERY_AUTHENTICATION_FAILED/);now+=7*86400000;assert.throws(()=>recovery.inspectRestore(seal.id),/RECOVERY_SEAL_REQUIRED/);assert.deepEqual(readdirSync(f.directory),[]);}finally{recovery.close();}});
test('checkpoint failure retains maintenance until explicit registered-work recovery',async()=>{const f=fixture();f.store.close();let failed=false;const recovery=new OfflineRecovery(f.file,f.directory,f.key,f.now,name=>{if(name==='phase:staged'&&!failed){failed=true;throw Error('SYNTHETIC_CHECKPOINT_FAILURE');}});try{await assert.rejects(()=>recovery.createSealedCheckpoint(),/SYNTHETIC_CHECKPOINT_FAILURE/);assert.throws(()=>new Store(f.file,f.now,true,'synthetic'),/INSTALLATION_MAINTENANCE/);assert.equal(recovery.recoverInterruptedActivation().recovered,true);assert.equal(recovery.authority.maintenanceState().mode,'ready');assert.deepEqual(readdirSync(f.directory),[]);assert.ok(!readdirSync(f.dir).some(name=>name.startsWith('.recovery-')));}finally{recovery.close();}});

test('trusted activation actually replaces missing or corrupt main without restoring authority or executing work',async()=>{for(const missing of [false,true]){const f=fixture();f.store.close();const recovery=new OfflineRecovery(f.file,f.directory,f.key,f.now);try{const seal=await recovery.createSealedCheckpoint(),authorityIdentity=recovery.authority.identity;if(missing)unlinkSync(f.file);else writeFileSync(f.file,'SYNTHETIC_CORRUPT_MAIN');const result=recovery.activateRestore({...seal,confirmation:'activate_sealed_checkpoint'});assert.equal(result.restoration_performed,true);assert.equal(result.execution_started,false);assert.equal(recovery.authority.identity,authorityIdentity);assert.equal(result.incarnation,1);assert.equal(recovery.authority.getSeal(),undefined);const store=new Store(f.file,f.now,true,'synthetic');try{assert.equal(store.history()[0].text,'SYNTHETIC_SEALED_CANARY');assert.equal((store.db.prepare('SELECT count(*) n FROM operations').get() as {n:number}).n,1);assert.equal((store.db.prepare('SELECT count(*) n FROM grants').get() as {n:number}).n,0);}finally{store.close();}assert.ok(!readdirSync(f.dir).some(name=>name.startsWith('.recovery-')));}finally{recovery.close();}}});
test('activation requires exact explicit confirmation and never activates ordinary or superseded IDs',async()=>{const f=fixture();f.store.close();const recovery=new OfflineRecovery(f.file,f.directory,f.key,f.now);try{const seal=await recovery.createSealedCheckpoint();assert.throws(()=>recovery.activateRestore({...seal,confirmation:'yes' as any}),/RECOVERY_CONFIRMATION_REQUIRED/);assert.throws(()=>recovery.activateRestore({...seal,seal_id:'10000000-0000-4000-8000-000000000001',confirmation:'activate_sealed_checkpoint'}),/RECOVERY_CONFIRMATION_STALE/);assert.equal(recovery.inspectRestore(seal.id).eligible,true);assert.equal(recovery.authority.maintenanceState().mode,'ready');}finally{recovery.close();}});
test('precommit failure rolls back byte-exact corrupt original bundle and preserves seal',async()=>{const f=fixture();f.store.close();let armed=false;const recovery=new OfflineRecovery(f.file,f.directory,f.key,f.now,name=>{if(armed&&name==='phase:verifying')throw Error('SYNTHETIC_VERIFY_FAILURE');});try{const seal=await recovery.createSealedCheckpoint();writeFileSync(f.file,'SYNTHETIC_ORIGINAL_CORRUPT');const original=readFileSync(f.file);armed=true;assert.throws(()=>recovery.activateRestore({...seal,confirmation:'activate_sealed_checkpoint'}),/SYNTHETIC_VERIFY_FAILURE/);assert.deepEqual(readFileSync(f.file),original);assert.equal(recovery.authority.maintenanceState().mode,'maintenance');assert.equal(recovery.recoverInterruptedActivation().rolled_back,true);assert.equal(recovery.authority.maintenanceState().mode,'ready');assert.equal(recovery.inspectRestore(seal.id).eligible,true);assert.throws(()=>new Store(f.file,f.now,true,'synthetic'));}finally{recovery.close();}});
test('postcommit failure stays fenced then only rolls forward, even after seal expiry',async()=>{const f=fixture();f.store.close();let armed=false,now=100000;const recovery=new OfflineRecovery(f.file,f.directory,f.key,()=>now,name=>{if(armed&&name==='phase:commit_decided'){armed=false;throw Error('SYNTHETIC_AFTER_COMMIT');}});try{const seal=await recovery.createSealedCheckpoint();writeFileSync(f.file,'SYNTHETIC_OLD_CORRUPT');armed=true;assert.throws(()=>recovery.activateRestore({...seal,confirmation:'activate_sealed_checkpoint'}),/SYNTHETIC_AFTER_COMMIT/);assert.throws(()=>new Store(f.file,()=>now,true,'synthetic'),/INSTALLATION_MAINTENANCE/);now+=8*86400000;assert.equal(recovery.recoverInterruptedActivation().restoration_performed,true);const store=new Store(f.file,()=>now,true,'synthetic');try{assert.equal(store.history()[0].text,'SYNTHETIC_SEALED_CANARY');}finally{store.close();}}finally{recovery.close();}});
test('unknown work file refuses cleanup and keeps both normal and MCP startup fenced',async()=>{const f=fixture();f.store.close();let armed=false;const recovery=new OfflineRecovery(f.file,f.directory,f.key,f.now,name=>{if(armed&&name==='phase:staged'){armed=false;const dir=readdirSync(f.dir).find(x=>x.startsWith('.recovery-'))!;writeFileSync(path.join(f.dir,dir,'unknown.private'),'SYNTHETIC_UNKNOWN');throw Error('SYNTHETIC_UNKNOWN_WORK');}});try{const seal=await recovery.createSealedCheckpoint();armed=true;assert.throws(()=>recovery.activateRestore({...seal,confirmation:'activate_sealed_checkpoint'}),/SYNTHETIC_UNKNOWN_WORK/);assert.throws(()=>recovery.recoverInterruptedActivation(),/RECOVERY_UNKNOWN_FILE/);assert.throws(()=>new Store(f.file,f.now,false,'synthetic'),/INSTALLATION_MAINTENANCE/);assert.equal(recovery.authority.maintenanceState().mode,'maintenance');}finally{recovery.close();}});
test('a missing current authority or wrong authorized key never permits activation',async()=>{const f=fixture();f.store.close();const recovery=new OfflineRecovery(f.file,f.directory,f.key,f.now);const seal=await recovery.createSealedCheckpoint();recovery.close();const wrong=new OfflineRecovery(f.file,f.directory,Buffer.alloc(32,20),f.now);try{assert.throws(()=>wrong.inspectRestore(seal.id),/RECOVERY_AUTHENTICATION_FAILED/);assert.equal(wrong.authority.maintenanceState().mode,'ready');}finally{wrong.close();}const before=readFileSync(f.file);unlinkSync(f.file+'.authority.sqlite');assert.throws(()=>new OfflineRecovery(f.file,f.directory,f.key,f.now),/PRIVACY_AUTHORITY_REQUIRED/);assert.deepEqual(readFileSync(f.file),before);});
test('changed staged candidate and failed rename intent retain fence until verified recovery',async()=>{for(const kind of ['changed','rename']){const f=fixture();f.store.close();let armed=false;const recovery=new OfflineRecovery(f.file,f.directory,f.key,f.now,name=>{if(!armed)return;if(kind==='changed'&&name==='phase:staged'){const dir=readdirSync(f.dir).find(x=>x.startsWith('.recovery-'))!;writeFileSync(path.join(f.dir,dir,'candidate.sqlite'),'SYNTHETIC_CHANGED_CANDIDATE');}if(kind==='rename'&&name==='rename:main:before'){armed=false;const error=Error('SYNTHETIC_RENAME_IO_FAILURE') as NodeJS.ErrnoException;error.code='EIO';throw error;}});try{const seal=await recovery.createSealedCheckpoint();armed=true;assert.throws(()=>recovery.activateRestore({...seal,confirmation:'activate_sealed_checkpoint'}),/RECOVERY_FILE_CHANGED|SYNTHETIC_RENAME_IO_FAILURE/);assert.equal(recovery.authority.maintenanceState().mode,'maintenance');if(kind==='changed')assert.throws(()=>recovery.recoverInterruptedActivation(),/RECOVERY_FILE_CHANGED/);else {assert.equal(recovery.recoverInterruptedActivation().rolled_back,true);assert.equal(recovery.authority.maintenanceState().mode,'ready');}}finally{recovery.close();}}});

test('stale coordinator cancellation and deletion-resume paths reject before raw database writes',async()=>{const f=fixture();const host:HostAdapter={async *startTurn(){},async *resumeExecution(){},async cancelTurn(){},async close(){}};const coordinator=new TurnCoordinator(f.store,host,undefined,f.key,f.now);try{f.store.authority.db.prepare('UPDATE installation SET incarnation=incarnation+1').run();await assert.rejects(()=>coordinator.cancelTurn(f.store.scope,'unrelated'),/INSTALLATION_HANDLE_STALE/);assert.throws(()=>coordinator.resumeDeletion(),/INSTALLATION_HANDLE_STALE/);}finally{await coordinator.close();f.store.close();}});
