// Multi-scope fixtures use attached trusted views (recover=false) under one authoritative owner. Independent runtime owners are tested as denied.
import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {fileURLToPath} from 'node:url';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,readFileSync,renameSync,existsSync,readdirSync,writeFileSync} from 'node:fs';
import os from 'node:os';import path from 'node:path';
import {Store,ProductError} from '@between/core/store';
import {TurnCoordinator} from '@between/core/runtime/turn-coordinator';
import {OffCache} from '@between/core/runtime/off-cache';
import {RuntimeService} from '@between/core/runtime/service';
import {requestSchema} from '@between/contracts/commands';
import {BackupManager} from '@between/core/privacy/backup';
import type {HostAdapter,HostTurn,HostEvent} from '@between/contracts/host';
class SyntheticHost implements HostAdapter {
 calls=0;cancels=0;gate?:Promise<void>;
 async *startTurn(_input:HostTurn):AsyncIterable<HostEvent>{this.calls++;if(this.gate)await this.gate;}
 resumeExecution(input:HostTurn){return this.startTurn(input);}
 async cancelTurn(){this.cancels++;}
 async close(){}
}
function fixture(memory=true,scope='synthetic-a'){
 let time=100000;const now=()=>time,dir=mkdtempSync(path.join(os.tmpdir(),'privacy-synthetic-')),file=path.join(dir,'main.sqlite'),store=new Store(file,now,true,scope);store.start(true,true,memory);const key=Buffer.alloc(32,11),off=new OffCache(path.join(dir,'spool.sqlite'),key,store.authority,now),host=new SyntheticHost(),coordinator=new TurnCoordinator(store,host,off,key,now);return {now,advance:(ms:number)=>time+=ms,dir,file,store,key,off,host,coordinator};
}
async function close(f:ReturnType<typeof fixture>){await f.coordinator.close();f.off.close();f.store.close();}
function seed(store:Store){const turn=store.receive(randomUUID(),'SYNTHETIC_PRIVATE_CANARY favorite blue')!;store.context(turn.token,{});store.remember(turn.token,'favorite blue','SYNTHETIC_PRIVATE_CANARY:operation');const pending=store.prepare(turn,'SYNTHETIC_PENDING_CANARY');return {turn,pending};}
function confirm(f:ReturnType<typeof fixture>,plan:ReturnType<Store['planDeletion']>){return f.coordinator.confirmDeletion(f.store.scope,plan.plan_id,plan.digest,plan.confirmation_token);}

test('whole relationship preview immediately suppresses reads, writes and old grants without physically deleting content',async()=>{const f=fixture();try{const {turn,pending}=seed(f.store);f.off.put(f.store.scope,'receipt','SYNTHETIC_SPOOL_CANARY');const before=(f.store.db.prepare('SELECT count(*) n FROM messages').get() as {n:number}).n;const plan=f.coordinator.planDeletion(f.store.scope);assert.equal(plan.kind,'whole_relationship');assert.equal(plan.expires_at,f.now()+600000);assert.deepEqual(f.store.history(),[]);assert.deepEqual(f.store.search('favorite'),[]);assert.equal((f.store.db.prepare('SELECT count(*) n FROM messages').get() as {n:number}).n,before);assert.equal((f.off.db.prepare('SELECT count(*) n FROM receipts').get() as {n:number}).n,1);assert.equal((f.store.db.prepare('SELECT text FROM messages WHERE id=?').get(pending.id) as {text:string}).text,'SYNTHETIC_PENDING_CANARY');assert.throws(()=>f.store.receive('late','SYNTHETIC late'),/RELATIONSHIP_SUPPRESSED/);assert.throws(()=>f.store.remember(turn.token,'favorite','late-write'),/RELATIONSHIP_SUPPRESSED/);assert.throws(()=>f.off.put(f.store.scope,'late','SYNTHETIC'),/RELATIONSHIP_SUPPRESSED/);assert.throws(()=>f.store.ack(pending.id),/RELATIONSHIP_SUPPRESSED/);assert.throws(()=>f.store.set({memory:'on',role:'active'}),/RELATIONSHIP_SUPPRESSED/);assert.equal(f.store.deletionStatus().online_records_cleared,false);}finally{await close(f);}});

test('cancel preview restores recoverable history but never old pending draft, grant, queued work or ACK',async()=>{const f=fixture();const {turn,pending}=seed(f.store);try{f.coordinator.accept(f.store.scope,randomUUID(),'SYNTHETIC runtime duplicate');await f.coordinator.idle();const plan=f.coordinator.planDeletion(f.store.scope);f.coordinator.cancelDeletion(f.store.scope,plan.plan_id);assert.equal(f.store.history().some(m=>m.id===pending.id),false);assert.ok(f.store.history().some(m=>m.text.includes('PRIVATE_CANARY')));assert.throws(()=>f.store.ack(pending.id),/STALE_REVISION/);assert.throws(()=>f.store.authorize(turn.token),/NOT_AUTHORIZED/);const file=f.file;await close(f);const next=new Store(file,f.now,true,'synthetic-a');try{assert.equal(next.history().some(m=>m.id===pending.id),false);assert.throws(()=>next.ack(pending.id),/STALE_REVISION/);}finally{next.close();}}catch(error){if(f.store.db.open)await close(f);throw error;}});

test('confirmation is one-use, trusted-scope-bound, exact digest-bound and expires at ten minutes',async()=>{const f=fixture();try{seed(f.store);const plan=f.coordinator.planDeletion(f.store.scope);assert.throws(()=>f.coordinator.planDeletion(f.store.scope),/DELETION_PLAN_EXISTS/);assert.throws(()=>f.coordinator.confirmDeletion('foreign',plan.plan_id,plan.digest,plan.confirmation_token),/NOT_AUTHORIZED/);assert.throws(()=>f.coordinator.confirmDeletion(f.store.scope,plan.plan_id,'0'.repeat(64),plan.confirmation_token),/DELETION_CONFIRMATION_INVALID/);assert.throws(()=>f.coordinator.confirmDeletion(f.store.scope,plan.plan_id,plan.digest,'wrong'),/DELETION_CONFIRMATION_INVALID/);f.advance(600000);assert.throws(()=>confirm(f,plan),/DELETION_CONFIRMATION_EXPIRED/);assert.equal(f.store.isSuppressed(),true);const fresh=f.coordinator.planDeletion(f.store.scope);assert.throws(()=>confirm(f,plan),/DELETION_CONFIRMATION_INVALID/);assert.equal(confirm(f,fresh).state,'deleted');assert.throws(()=>confirm(f,fresh),/DELETION_CONFIRMATION_INVALID|DELETION_CONFIRMATION_USED/);assert.throws(()=>f.coordinator.cancelDeletion(f.store.scope,fresh.plan_id),/DELETION_ALREADY_STARTED/);}finally{await close(f);}});

test('preview inventory rejects new or changed scoped content, including a late direct storage fault',async()=>{const f=fixture();try{const {turn}=seed(f.store);const plan=f.coordinator.planDeletion(f.store.scope);f.store.db.prepare('UPDATE sources SET text=? WHERE id=?').run('SYNTHETIC changed',turn.source);assert.throws(()=>confirm(f,plan),/DELETION_PREVIEW_STALE/);assert.throws(()=>f.coordinator.cancelDeletion(f.store.scope,plan.plan_id),/DELETION_PREVIEW_STALE/);assert.equal(f.store.isSuppressed(),true);}finally{await close(f);}});

test('confirmed deletion clears all controlled content, orphan FTS, operation bodies and spool; other scope survives',async()=>{const f=fixture(),other=new Store(f.file,f.now,false,'synthetic-b');try{other.start(true,true,true);const {turn,pending}=seed(f.store);const b=other.receive('same-source','SYNTHETIC_OTHER_SCOPE')!;other.context(b.token,{});other.remember(b.token,'SYNTHETIC_OTHER_SCOPE','other-operation');f.store.db.prepare('INSERT INTO memory_fts(id,scope,text) VALUES(?,?,?)').run('orphan',f.store.scope,'SYNTHETIC_ORPHAN_FTS_CANARY');f.off.put(f.store.scope,'receipt','SYNTHETIC_SPOOL_CANARY');f.off.put(other.scope,'receipt','SYNTHETIC_OTHER_SPOOL');f.coordinator.accept(f.store.scope,randomUUID(),'SYNTHETIC_RUNTIME_BODY_CANARY');await f.coordinator.idle();const plan=f.coordinator.planDeletion(f.store.scope);assert.equal(confirm(f,plan).state,'deleted');for(const table of ['sources','memories','messages','pending','events','grants','tool_audit','operations','scope_controls','scope_safety','business_versions'])assert.equal((f.store.db.prepare(`SELECT count(*) n FROM ${table} WHERE scope=?`).get(f.store.scope) as {n:number}).n,0,table);assert.equal((f.store.db.prepare('SELECT count(*) n FROM memory_fts WHERE scope=?').get(f.store.scope) as {n:number}).n,0);assert.equal((f.store.db.prepare('SELECT count(*) n FROM runtime_turns WHERE conversation_id=?').get(f.store.scope) as {n:number}).n,0);assert.equal(f.off.get(other.scope,'receipt'),'SYNTHETIC_OTHER_SPOOL');assert.equal(other.history()[0].text,'SYNTHETIC_OTHER_SCOPE');assert.throws(()=>f.store.context(turn.token,{}),/RELATIONSHIP_DELETED/);assert.throws(()=>f.store.ack(pending.id),/RELATIONSHIP_DELETED/);assert.throws(()=>f.store.start(true,true,true),/RELATIONSHIP_DELETED/);assert.equal(f.store.transient.size,0);assert.equal(f.store.ephemeral.size,0);assert.ok(!readFileSync(f.file).includes(Buffer.from('SYNTHETIC_PRIVATE_CANARY')));assert.ok(!readFileSync(f.file).includes(Buffer.from('SYNTHETIC_RUNTIME_BODY_CANARY')));assert.ok(!JSON.stringify(f.store.authority.db.prepare('SELECT * FROM plans').all()).includes('CANARY'));assert.equal(f.store.deletionStatus().plan!.physical_media_erasure,false);assert.deepEqual(f.store.deletionStatus().plan!.uncontrolled_copies,['host_history','model_provider_history','platform_logs']);}finally{other.close();await close(f);}});

test('delete waits for actual host quiescence and automatically completes after the generator settles',async()=>{const f=fixture();let release!:()=>void;f.host.gate=new Promise<void>(resolve=>release=resolve);try{f.coordinator.accept(f.store.scope,randomUUID(),'SYNTHETIC_INFLIGHT');const plan=f.coordinator.planDeletion(f.store.scope);assert.equal(confirm(f,plan).state,'cleaning');assert.equal(f.store.deletionStatus().plan!.step,'quiesce');assert.ok((f.store.db.prepare('SELECT count(*) n FROM runtime_turns').get() as {n:number}).n>0);assert.throws(()=>f.coordinator.accept(f.store.scope,randomUUID(),'SYNTHETIC_LATE'),/RELATIONSHIP_DELETED/);release();await f.coordinator.idle();assert.equal(f.store.deletionStatus().state,'deleted');assert.equal(f.host.calls,1);}finally{release();await close(f);}});

test('cleanup failure remains suppressed and resumes idempotently after restart without executing old work',async()=>{const f=fixture();seed(f.store);const plan=f.coordinator.planDeletion(f.store.scope);const original=f.store.verifyRelationshipErased.bind(f.store);f.store.verifyRelationshipErased=()=>{throw new ProductError('SYNTHETIC_CRASH_WINDOW');};assert.equal(confirm(f,plan).state,'cleaning');assert.match(f.store.deletionStatus().plan!.step,/blocked:SYNTHETIC_CRASH_WINDOW/);assert.equal((f.store.db.prepare('SELECT count(*) n FROM messages').get() as {n:number}).n,0);f.store.verifyRelationshipErased=original;await close(f);const next=new Store(f.file,f.now,true,'synthetic-a'),off=new OffCache(path.join(f.dir,'spool.sqlite'),f.key,next.authority,f.now),host=new SyntheticHost(),coordinator=new TurnCoordinator(next,host,off,f.key,f.now);try{coordinator.start();await coordinator.idle();assert.equal(next.deletionStatus().state,'deleted');assert.equal(host.calls,0);assert.equal(next.authority.get(next.scope)!.generation,1);assert.equal(coordinator.resumeDeletion().state,'deleted');assert.throws(()=>next.start(true,true,true),/RELATIONSHIP_DELETED/);}finally{await coordinator.close();off.close();next.close();}const brandNew=new Store(f.file,f.now,true,'new-relationship-id');try{assert.equal(brandNew.controls().started,false);brandNew.start(true,true,true);assert.deepEqual(brandNew.history(),[]);}finally{brandNew.close();}});

test('restart of pending preview does not physically delete pending body or grant new service authority',async()=>{const f=fixture();const {pending}=seed(f.store);const plan=f.coordinator.planDeletion(f.store.scope);await close(f);const next=new Store(f.file,f.now,true,'synthetic-a'),off=new OffCache(path.join(f.dir,'spool.sqlite'),f.key,next.authority,f.now),coordinator=new TurnCoordinator(next,new SyntheticHost(),off,f.key,f.now);try{assert.equal((next.db.prepare('SELECT text FROM messages WHERE id=?').get(pending.id) as {text:string}).text,'SYNTHETIC_PENDING_CANARY');assert.equal(next.history().length,0);assert.equal(coordinator.confirmDeletion(next.scope,plan.plan_id,plan.digest,plan.confirmation_token).state,'deleted');}finally{await coordinator.close();off.close();next.close();}});

test('unknown-scope FTS residue prevents false completion; missing spool also stays blocked',async()=>{for(const failure of ['fts','spool']){const f=fixture();try{seed(f.store);if(failure==='fts')f.store.db.prepare('INSERT INTO memory_fts(id,scope,text) VALUES(?,NULL,?)').run('unknown','SYNTHETIC_UNKNOWN_FTS');else f.off.removeScope=()=>{throw new ProductError('DELETION_SPOOL_UNAVAILABLE');};const plan=f.coordinator.planDeletion(f.store.scope);assert.equal(confirm(f,plan).state,'cleaning');assert.equal(f.store.deletionStatus().online_records_cleared,false);assert.match(f.store.deletionStatus().plan!.step,/blocked:DELETION_(FTS_VERIFICATION_FAILED|SPOOL_UNAVAILABLE)/);}finally{await close(f);}}});

test('main/authority crash gap cannot recover or continue using stale control permissions',async()=>{const f=fixture();f.store.authority.advance(f.store.scope,f.store.authority.get(f.store.scope)!.version);assert.throws(()=>f.store.receive('late','SYNTHETIC'),/PRIVACY_AUTHORITY_MISMATCH/);await close(f);assert.throws(()=>new Store(f.file,f.now,true,'synthetic-a'),/PRIVACY_AUTHORITY_MISMATCH/);});

test('existing authority cannot silently reinitialize when missing, including a backup-shaped main database',async()=>{const f=fixture();await close(f);const bytes=readFileSync(f.file);renameSync(f.file+'.authority.sqlite',f.file+'.authority.saved');assert.throws(()=>new Store(f.file,f.now,true,'synthetic-a'),/PRIVACY_AUTHORITY_REQUIRED/);assert.deepEqual(readFileSync(f.file),bytes);assert.equal(existsSync(f.file+'.authority.sqlite'),false);const copy=path.join(f.dir,'copied.sqlite');writeFileSync(copy,bytes);assert.throws(()=>new Store(copy,f.now,true,'synthetic-a'),/PRIVACY_AUTHORITY_REQUIRED/);});

test('encrypted main-only backups exclude spool; validation strips execution rights and never activates or swaps',async()=>{const f=fixture(false);try{f.coordinator.accept(f.store.scope,randomUUID(),'SYNTHETIC_OFF_BACKUP_CANARY');await f.coordinator.idle();const manager=new BackupManager(f.store,path.join(f.dir,'backups'),f.key,f.now),backup=await manager.create();assert.equal(backup.encrypted,true);assert.ok(!readFileSync(path.join(manager.directory,backup.id+'.relbackup')).includes(Buffer.from('SYNTHETIC_OFF_BACKUP_CANARY')));const before=readFileSync(f.file),report=manager.validateRestore(backup.id);assert.deepEqual(report,{validated:true,restoration_performed:false,activation_supported:false,staged_grants:0,staged_pending:0,expires_at:backup.expires_at});assert.deepEqual(readFileSync(f.file),before);assert.ok(readdirSync(manager.directory).every(name=>name.endsWith('.relbackup')));assert.equal((f.off.db.prepare('SELECT count(*) n FROM receipts').get() as {n:number}).n,1);}finally{await close(f);}});

test('older backup cannot roll back memory-off, role pause or nickname restriction',async()=>{for(const changes of [{memory:'off' as const},{role:'paused' as const},{nicknameState:'suspended' as const}]){const f=fixture();try{seed(f.store);const manager=new BackupManager(f.store,path.join(f.dir,'backups'),f.key,f.now),backup=await manager.create();f.store.set(changes);assert.throws(()=>manager.validateRestore(backup.id),/BACKUP_STALE_AUTHORITY/);}finally{await close(f);}}});

test('old operation ledger and revoked grants cannot come back through backup validation',async()=>{const f=fixture();try{const t=f.store.receive('first','SYNTHETIC operation')!;f.store.context(t.token,{});const manager=new BackupManager(f.store,path.join(f.dir,'backups'),f.key,f.now),backup=await manager.create();f.store.remember(t.token,'operation','first-operation');assert.throws(()=>manager.validateRestore(backup.id),/BACKUP_STALE_AUTHORITY/);const current=await manager.create();f.store.end(t,t.id,'ended');assert.throws(()=>manager.validateRestore(current.id),/BACKUP_STALE_BUSINESS_STATE/);assert.equal((f.store.db.prepare('SELECT count(*) n FROM operations').get() as {n:number}).n,1);}finally{await close(f);}});

test('deleted relationship rejects old backup and honestly reports retained encrypted copy until actual expiry cleanup',async()=>{const f=fixture();try{seed(f.store);const manager=new BackupManager(f.store,path.join(f.dir,'backups'),f.key,f.now),backup=await manager.create(),file=path.join(manager.directory,backup.id+'.relbackup');const plan=f.coordinator.planDeletion(f.store.scope);assert.equal(plan.backup_expires_at,backup.expires_at);assert.equal(confirm(f,plan).state,'deleted');assert.equal(f.store.deletionStatus().backups_physically_cleared,false);assert.ok(existsSync(file));assert.throws(()=>manager.validateRestore(backup.id),/RELATIONSHIP_DELETED/);f.advance(7*86400000);assert.equal(f.store.deletionStatus().backups_physically_cleared,false);manager.expire();assert.equal(existsSync(file),false);assert.equal(f.store.deletionStatus().backups_physically_cleared,true);}finally{await close(f);}});

test('backup authentication, traversal, unknown schema and missing current authority fail closed',async()=>{const f=fixture();try{const manager=new BackupManager(f.store,path.join(f.dir,'backups'),f.key,f.now),backup=await manager.create(),file=path.join(manager.directory,backup.id+'.relbackup');assert.throws(()=>manager.validateRestore('../main.sqlite'));const bytes=readFileSync(file);bytes[bytes.length-1]^=1;writeFileSync(file,bytes);assert.throws(()=>manager.validateRestore(backup.id),/BACKUP_AUTHENTICATION_FAILED/);f.store.db.exec('CREATE TABLE unexpected_private_body(body TEXT)');await assert.rejects(()=>manager.create(),/BACKUP_UNSUPPORTED_TABLE/);f.store.db.exec('DROP TABLE unexpected_private_body');renameSync(f.store.authority.file,f.store.authority.file+'.unavailable');assert.throws(()=>manager.validateRestore(backup.id),/PRIVACY_AUTHORITY_REQUIRED/);}finally{await close(f);}});

test('trusted deletion protocol requires exact explicit confirmation and denies extra targets or model-style instructions',async()=>{const f=fixture();try{const service=new RuntimeService(f.store,f.coordinator);assert.equal(requestSchema.safeParse({schema_version:1,id:randomUUID(),action:'plan_deletion',conversation_id:f.store.scope,kind:'topic'}).success,false);const response=await service.handle({schema_version:1,id:randomUUID(),action:'plan_deletion',conversation_id:f.store.scope,kind:'whole_relationship'}) as {plan:ReturnType<Store['planDeletion']>};const plan=response.plan;for(const confirmation of ['okay','👍','delete everything elsewhere'])assert.equal(requestSchema.safeParse({schema_version:1,id:randomUUID(),action:'confirm_deletion',conversation_id:f.store.scope,plan_id:plan.plan_id,digest:plan.digest,confirmation_token:plan.confirmation_token,confirmation}).success,false);await assert.rejects(()=>service.handle({schema_version:1,id:randomUUID(),action:'resume_deletion',conversation_id:'foreign'}),/NOT_AUTHORIZED/);await service.handle({schema_version:1,id:randomUUID(),action:'confirm_deletion',conversation_id:f.store.scope,plan_id:plan.plan_id,digest:plan.digest,confirmation_token:plan.confirmation_token,confirmation:'confirm_delete_this_relationship'});assert.equal(f.store.deletionStatus().state,'deleted');}finally{await close(f);}});

test('meaningful memories persist past thirty days, while retained source evidence is reduced to exact quotes',async()=>{const f=fixture();try{const t=f.store.receive('old','SYNTHETIC_DISCARD_OLD_CONTEXT I like blue OTHER_OLD_CONTEXT')!;f.store.context(t.token,{});f.store.remember(t.token,'I like blue','memory');f.store.end(t,t.id,'done');f.advance(30*86400000+1);f.store.purge();assert.equal(f.store.history().length,0);assert.equal((f.store.db.prepare('SELECT count(*) n FROM memories').get() as {n:number}).n,1);assert.equal((f.store.db.prepare('SELECT text FROM sources WHERE id=?').get(t.source) as {text:string}).text,'I like blue');assert.equal(f.store.search('blue').length,1);}finally{await close(f);}});

test('live registered plaintext backup work prevents deletion completion and cannot be reaped as abandoned',async()=>{const f=fixture();try{seed(f.store);const manager=new BackupManager(f.store,path.join(f.dir,'backups'),f.key,f.now),work=f.store.authority.beginWork('create');writeFileSync(path.join(work.temporary,'main.sqlite'),'SYNTHETIC_TEMP_CANARY',{mode:0o600});f.store.authority.recoverAbandonedWork();assert.ok(existsSync(work.temporary));const plan=f.coordinator.planDeletion(f.store.scope);assert.equal(confirm(f,plan).state,'cleaning');assert.match(f.store.deletionStatus().plan!.step,/DELETION_BACKUP_WORK_PENDING/);assert.equal(f.store.deletionStatus().online_records_cleared,false);f.store.authority.finishWork(work.id);assert.equal(existsSync(work.temporary),false);assert.equal(f.coordinator.resumeDeletion().state,'deleted');manager.close();}finally{await close(f);}});

test('abandoned registered backup plaintext is recovered before deleted scope can complete',async()=>{const f=fixture();try{const manager=new BackupManager(f.store,path.join(f.dir,'backups'),f.key,f.now),work=f.store.authority.beginWork('validate');writeFileSync(path.join(work.temporary,'main.sqlite'),'SYNTHETIC_ABANDONED_CANARY',{mode:0o600});f.store.authority.db.prepare("UPDATE backup_work SET status='cleanup' WHERE id=?").run(work.id);const plan=f.coordinator.planDeletion(f.store.scope);assert.equal(confirm(f,plan).state,'deleted');assert.equal(existsSync(work.temporary),false);assert.equal((f.store.authority.db.prepare('SELECT count(*) n FROM backup_work').get() as {n:number}).n,0);manager.close();}finally{await close(f);}});

test('unknown registered-temp entries and unsupported main tables prevent unverified cleanup claims',async()=>{for(const kind of ['temp','table']){const f=fixture();try{const manager=new BackupManager(f.store,path.join(f.dir,'backups'),f.key,f.now);if(kind==='temp'){const work=f.store.authority.beginWork('create');writeFileSync(path.join(work.temporary,'unexpected.private'),'SYNTHETIC_KEEP');f.store.authority.db.prepare("UPDATE backup_work SET status='cleanup' WHERE id=?").run(work.id);}else f.store.db.exec('CREATE TABLE new_unintegrated_feature(body TEXT)');const plan=f.coordinator.planDeletion(f.store.scope);assert.equal(confirm(f,plan).state,'cleaning');assert.match(f.store.deletionStatus().plan!.step,/BACKUP_TEMP_UNVERIFIED|DELETION_UNSUPPORTED_TABLE/);manager.close();}finally{await close(f);}}});

test('idle backup manager sweeps expired archives and reports cleanup only after removal',async()=>{const f=fixture();try{const manager=new BackupManager(f.store,path.join(f.dir,'backups'),f.key,f.now),backup=await manager.create();f.advance(7*86400000);assert.ok(existsSync(path.join(manager.directory,backup.id+'.relbackup')));await new Promise(resolve=>setTimeout(resolve,1100));assert.equal(existsSync(path.join(manager.directory,backup.id+'.relbackup')),false);assert.equal(f.store.deletionStatus().backups_physically_cleared,true);assert.equal(manager.maintenanceStatus().expiry_error,null);manager.close();}finally{await close(f);}});

async function killAtCheckpoint(mode:string,directory:string){
 const child=spawn(process.execPath,[fileURLToPath(new URL('./privacy-process-fixture.js',import.meta.url)),mode,directory],{stdio:['ignore','pipe','pipe']});
 let output='',errors='',timeout:ReturnType<typeof setTimeout>|undefined,interval:ReturnType<typeof setInterval>|undefined;
 const exit=once(child,'exit');void exit.catch(()=>{});child.stdout.on('data',chunk=>output+=chunk.toString());child.stderr.on('data',chunk=>errors+=chunk.toString());
 try{await new Promise<void>((resolve,reject)=>{timeout=setTimeout(()=>reject(Error('Synthetic checkpoint timeout: '+errors)),10000);interval=setInterval(()=>{if(child.exitCode!==null||child.signalCode!==null)reject(Error('Synthetic checkpoint exited before kill: '+errors));else if(output.includes('CHECKPOINT_'))resolve();},10);});
  if(child.exitCode!==null||child.signalCode!==null)throw Error('Synthetic checkpoint exited before kill');
  if(!child.kill('SIGKILL'))throw Error('Synthetic SIGKILL was not delivered');const [,signal]=await exit;assert.equal(signal,'SIGKILL');
 }finally{clearTimeout(timeout);clearInterval(interval);if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');await exit.catch(()=>{});}
}


test('actual SIGKILL after durable deletion confirmation resumes cleanup without reexecuting committed operations',async()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'privacy-kill-delete-'));await killAtCheckpoint('confirmed',dir);const store=new Store(path.join(dir,'main.sqlite'),()=>100000,true,'crash-scope'),host=new SyntheticHost(),coordinator=new TurnCoordinator(store,host);try{assert.equal(store.deletionStatus().state,'cleaning');coordinator.start();await coordinator.idle();assert.equal(store.deletionStatus().state,'deleted');assert.equal(host.calls,0);assert.equal((store.db.prepare('SELECT count(*) n FROM operations').get() as {n:number}).n,0);assert.ok(!readFileSync(store.file).includes(Buffer.from('SYNTHETIC_PROCESS_PRIVATE_CANARY')));}finally{await coordinator.close();store.close();}});

test('actual SIGKILL during plaintext backup is recovered by ordinary Store startup without a manager or key',async()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'privacy-kill-backup-'));await killAtCheckpoint('backup',dir);const temporary=path.join(dir,'backups',readdirSync(path.join(dir,'backups')).find(name=>name.startsWith('.stage-'))!);assert.ok(readFileSync(path.join(temporary,'main.sqlite')).includes(Buffer.from('SYNTHETIC_PROCESS_PRIVATE_CANARY')));const store=new Store(path.join(dir,'main.sqlite'),()=>100000,true,'crash-scope');try{assert.equal(existsSync(temporary),false);const manager=new BackupManager(store,path.join(dir,'backups'),Buffer.alloc(32,11),()=>100000);assert.equal(existsSync(temporary),false);assert.equal((store.authority.db.prepare('SELECT count(*) n FROM backup_work').get() as {n:number}).n,0);const coordinator=new TurnCoordinator(store,new SyntheticHost());try{const plan=coordinator.planDeletion(store.scope);assert.equal(coordinator.confirmDeletion(store.scope,plan.plan_id,plan.digest,plan.confirmation_token).state,'deleted');}finally{await coordinator.close();manager.close();}}finally{store.close();}});

test('actual SIGKILL between independent authority advance and main commit refuses stale service restart',async()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'privacy-kill-authority-'));await killAtCheckpoint('authority',dir);assert.throws(()=>new Store(path.join(dir,'main.sqlite'),()=>100000,true,'crash-scope'),/PRIVACY_AUTHORITY_MISMATCH/);});

test('crash harness detects premature fixture exit and clears all polling handles',async()=>{const dir=mkdtempSync(path.join(os.tmpdir(),'privacy-early-exit-'));await assert.rejects(()=>killAtCheckpoint('early-exit',dir),/Synthetic checkpoint exited before kill/);});
