import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,readFileSync} from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store,parseControls,ProductError} from '@between/core/store';
const event=()=>crypto.randomUUID();
function setup(memory=true){const dir=mkdtempSync(path.join(os.tmpdir(),'relationship-test-'));const store=new Store(path.join(dir,'state.db'));store.start(true,true,memory);return store;}
test('明确成年/告知未确认不能开始，默认关闭记忆',()=>{const s=setup(false);assert.equal(s.controls().memory,'off');assert.throws(()=>s.start(false,true,true),/CONSENT_REQUIRED/);s.close();});
test('朋友与称呼同批独立生效；撤回没有自动恢复',()=>{const s=setup();const t=s.receive(event(),'叫我夜猫子吧，不过只做朋友')!;assert.equal(s.controls().nickname,'夜猫子');assert.equal(s.controls().direction,'friends');s.end(t,'unused','done');s.receive(event(),'夜猫子先别叫了');assert.equal(s.controls().nicknameState,'suspended');s.receive(event(),'喜欢跟你聊');assert.equal(s.controls().direction,'friends');assert.equal(s.controls().nicknameState,'suspended');s.close();});
test('独立审查回归：引用、否定和疑问不授予/改变控制',()=>{const s=setup();for(const text of ['我没有说要叫我宝贝','不要关闭记忆','“关闭记忆”是什么意思？','小说里说：叫我宝贝','为什么只做朋友？'])assert.deepEqual(parseControls(text,s.controls()),{});assert.equal(s.controls().memory,'on');s.close();});
test('原规格无逗号多意图：叫我夜猫子但只做朋友',()=>{const s=setup();s.receive(event(),'叫我夜猫子但只做朋友');assert.equal(s.controls().nickname,'夜猫子');assert.equal(s.controls().direction,'friends');s.close();});
test('独立审查回归：超过1000条时取最近历史并保持顺序',()=>{const s=setup();const statement=s.db.prepare('INSERT INTO messages(id,role,text,status,at,scope) VALUES(?,?,?,?,?,?)');s.db.transaction(()=>{for(let i=0;i<1002;i++)statement.run(String(i),'user','row'+i,'confirmed',i+Date.now(),s.scope);})();const rows=s.history();assert.equal(rows.length,1000);assert.equal(rows[0].text,'row2');assert.equal(rows.at(-1)?.text,'row1001');s.close();});
test('重复ID不生成第二轮，同文新ID是新消息',()=>{const s=setup();const id=event();assert.ok(s.receive(id,'你好'));assert.equal(s.receive(id,'你好'),null);assert.ok(s.receive(event(),'你好'));assert.equal(s.history().length,2);s.close();});
test('MCP必须先读上下文；伪造来源引文被拒绝；重复记忆幂等',()=>{const s=setup();const t=s.receive(event(),'我喜欢灰蓝色')!;assert.throws(()=>s.remember(t.token,'我喜欢灰蓝色',t.id+':我喜欢灰蓝色'),/CONTEXT_REQUIRED/);s.context(t.token,{});assert.throws(()=>s.remember(t.token,'我讨厌红色',t.id+':我讨厌红色'),/INVALID_SOURCE/);assert.equal(s.remember(t.token,'我喜欢灰蓝色',t.id+':我喜欢灰蓝色').result.id,s.remember(t.token,'我喜欢灰蓝色',t.id+':我喜欢灰蓝色').result.id);assert.equal((s.db.prepare('select count(*) n from memories').get() as any).n,1);s.close();});
test('旧grant/伪造grant/关闭记忆前在途回复全部失效',()=>{const s=setup();const t=s.receive(event(),'我喜欢蓝色')!;s.context(t.token,{});s.set({memory:'off'});assert.throws(()=>s.prepare(t,'旧回复'),/NOT_AUTHORIZED/);assert.throws(()=>s.context('made-up',{}),/NOT_AUTHORIZED/);s.close();});
test('关闭记忆不读取旧记录、不新增长期正文、必要称呼撤回重启保留',()=>{const s=setup();s.receive(event(),'叫我夜猫子吧');s.set({memory:'off'});s.receive(event(),'夜猫子先别叫了，这里有秘密 OFF_SECRET');assert.equal(s.search('夜猫子').length,0);const rows=JSON.stringify(s.db.prepare('select * from sources').all());assert.ok(!rows.includes('OFF_SECRET'));const file=s.file;s.close();const next=new Store(file);assert.equal(next.history().length,0);assert.equal(next.controls().nicknameState,'suspended');next.close();});
test('实际SQLite重启恢复on聊天与朋友方向，旧授权失效',()=>{const s=setup();const t=s.receive(event(),'只做朋友')!;s.context(t.token,{});const m=s.prepare(t,'好，我们就这样慢慢聊。');s.ack(m.id);const file=s.file;s.close();const next=new Store(file);assert.equal(next.history().length,2);assert.equal(next.controls().direction,'friends');assert.equal(next.history()[1].status,'confirmed');assert.throws(()=>next.context(t.token,{}),/NOT_AUTHORIZED/);next.close();});
test('未渲染输出保持pending；禁止称呼硬闸门',()=>{const s=setup();s.receive(event(),'叫我夜猫子吧');s.receive(event(),'夜猫子先别叫了');const t=s.receive(event(),'你好')!;s.context(t.token,{});assert.throws(()=>s.prepare(t,'夜猫子你好'),/BOUNDARY_VIOLATION/);const m=s.prepare(t,'你好');assert.equal(s.history().at(-1)?.status,'pending');s.ack(m.id);assert.equal(s.history().at(-1)?.status,'confirmed');s.close();});
test('独立审查回归：撤回清除未显示昵称草稿，重启不恢复无ack输出',()=>{const s=setup();s.receive(event(),'叫我夜猫子吧');const t=s.receive(event(),'你好')!;s.context(t.token,{});const m=s.prepare(t,'夜猫子你好');s.set({nicknameState:'suspended'});assert.ok(!s.history().some(x=>x.id===m.id));assert.throws(()=>s.ack(m.id),/STALE_REVISION/);const t2=s.receive(event(),'再来')!;s.context(t2.token,{});const m2=s.prepare(t2,'你好');const file=s.file;s.close();const next=new Store(file);assert.ok(!next.history().some(x=>x.id===m2.id));next.close();});
test('授权十分钟到期，角色停止/恢复使用XState状态转换',()=>{let now=100000;const dir=mkdtempSync(path.join(os.tmpdir(),'relationship-time-'));const s=new Store(path.join(dir,'s.db'),()=>now);s.start(true,true,true);const t=s.receive(event(),'你好')!;now+=600000;assert.throws(()=>s.context(t.token,{}),/NOT_AUTHORIZED/);s.set({role:'paused'});assert.equal(s.controls().role,'paused');s.set({role:'active'});assert.equal(s.controls().role,'active');s.close();});
test('off临时聊天四小时到点清理，当前称呼控制仍保留',()=>{let now=100000;const dir=mkdtempSync(path.join(os.tmpdir(),'relationship-off-time-'));const s=new Store(path.join(dir,'s.db'),()=>now);s.start(true,true,false);s.receive(event(),'叫我夜猫子吧');assert.equal(s.history().length,1);now+=4*3600000;assert.equal(s.history().length,0);assert.equal(s.controls().nickname,'夜猫子');s.close();});
