import test from 'node:test';import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,symlinkSync,unlinkSync,renameSync,linkSync,realpathSync} from 'node:fs';import os from 'node:os';import path from 'node:path';
import {readVerifiedContent,readBoundedDescriptor} from '@between/host-qwen/verified-read';
function fixture(){const root=mkdtempSync(path.join(os.tmpdir(),'verified-read-')),outside=mkdtempSync(path.join(os.tmpdir(),'outside-read-'));mkdirSync(path.join(root,'assets'));writeFileSync(path.join(root,'assets','skill.md'),'SYNTHETIC trusted skill');writeFileSync(path.join(outside,'skill.md'),'SYNTHETIC_OUTSIDE_CANARY');return {root,outside,file:path.join(root,'assets','skill.md')};}
test('descriptor-verified content read succeeds only for bounded regular root asset',async()=>{const f=fixture();assert.equal((await readVerifiedContent(f.root,f.file)).toString(),'SYNTHETIC trusted skill');await assert.rejects(()=>readVerifiedContent(f.root,f.file,3),/HOST_APP_ASSET_UNVERIFIED/);await assert.rejects(()=>readVerifiedContent(f.root,path.join(f.outside,'skill.md')),/HOST_APP_ASSET_UNVERIFIED/);});
test('initially verified leaf replaced by symlink is denied at actual read',async()=>{const f=fixture();assert.equal(realpathSync(f.file),f.file);unlinkSync(f.file);symlinkSync(path.join(f.outside,'skill.md'),f.file);await assert.rejects(()=>readVerifiedContent(f.root,f.file));});
test('initially verified parent replaced by external symlink is denied at actual read',async()=>{const f=fixture();assert.equal(realpathSync(f.file),f.file);renameSync(path.join(f.root,'assets'),path.join(f.root,'original'));symlinkSync(f.outside,path.join(f.root,'assets'));await assert.rejects(()=>readVerifiedContent(f.root,f.file));});
test('hardlink alias to outside content is rejected instead of reading',async()=>{const f=fixture();unlinkSync(f.file);linkSync(path.join(f.outside,'skill.md'),f.file);await assert.rejects(()=>readVerifiedContent(f.root,f.file),/HOST_APP_ASSET_UNVERIFIED/);});

test('descriptor read stays bounded even when content grows after initial stat',async()=>{let calls=0,requested=0;const fakeGrowingDescriptor={async read(buffer:Buffer,offset:number,length:number){calls++;requested+=length;buffer.fill(65,offset,offset+length);return {bytesRead:length};}};const result=await readBoundedDescriptor(fakeGrowingDescriptor,9);assert.equal(result.length,9);assert.equal(requested,9);assert.equal(calls,1);});
