const bridge=window.relationship;
const $=id=>document.getElementById(id);
const icons={chat:'M10 2c-5 0-9 3-9 7s3 7 8 7h1l-4 3v-4c10 3 18-8 4-13z',contacts:'M10 3a4 4 0 1 0 0 8a4 4 0 1 0 0-8M3 18c0-4 3-6 7-6s7 2 7 6M16 7h4M17 10h3',cube:'M10 2l8 4v10l-8 4-8-4V6zM2 6l8 5 8-5M10 11v9',folder:'M2 6V3h6l2 3h8v11H2zM2 7h16',phone:'M5 1h10v18H5zM9 16h2',menu:'M2 4h16M2 10h16M2 16h16',more:'M3 10h.1M10 10h.1M17 10h.1',emoji:'M10 2a8 8 0 1 0 0 16a8 8 0 1 0 0-16M6 8h.1M14 8h.1M6 12q4 5 8 0',scissors:'M5 12a3 3 0 1 0 0 6a3 3 0 1 0 0-6M15 12a3 3 0 1 0 0 6a3 3 0 1 0 0-6M4 2l11 13M16 2L5 15',bubble:'M10 2c-5 0-8 3-8 7s3 7 8 7h1l4 3v-5c2-1 3-3 3-5s-3-7-8-7M6 9h.1M10 9h.1M14 9h.1',call:'M4 2l4 4-3 3q2 4 6 6l3-3 4 4q-2 4-6 2Q3 16 2 7q0-3 2-5',video:'M2 5h11v11H2zM13 9l5-3v10l-5-3'};
for(const b of document.querySelectorAll('[data-icon]')){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 20 20');const p=document.createElementNS(svg.namespaceURI,'path');p.setAttribute('d',icons[b.dataset.icon]);if(b.dataset.icon==='more'){p.setAttribute('stroke-width','3');}svg.append(p);b.append(svg);}
document.querySelector('.close').onclick=()=>bridge.window('close');document.querySelector('.min').onclick=()=>bridge.window('minimize');document.querySelector('.max').onclick=()=>bridge.window('maximize');
let deletionRequestPending=false,deletionRequestUncertain=false,deletionRequestEpoch=0;
let lastRender='',state,composing=false,busy=false,controlGeneration=0,visual=new URLSearchParams(location.search).has('visual');
function avatar(who,fixture){const el=document.createElement('div');el.className='avatar';el.textContent=who==='user'?'你':'岚';if(fixture){el.textContent='';const img=document.createElement('img');img.src=fixture;el.append(img);}return el;}
function message(m){const row=document.createElement('div');row.className='message'+(m.role==='user'?' me':'')+(m.image?' image':'');row.dataset.id=m.id||'';row.append(avatar(m.role,m.avatar));const bubble=document.createElement('div');bubble.className='bubble';if(m.image){const img=document.createElement('img');img.src=m.image;img.alt='参考截图中的猫，仅用于视觉测试';bubble.append(img);}else bubble.textContent=m.text;row.append(bubble);return row;}
function system(text,error=false){const p=document.createElement('div');p.className='system'+(error?' error':'');p.textContent=text;$('messages').append(p);$('messages').scrollTop=$('messages').scrollHeight;}
function deletionBlocked(s){return !!s?.deletion&&s.deletion.state!=='active';}
function sendingBlocked(){return deletionBlocked(state)||deletionRequestPending||deletionRequestUncertain;}
function localDeletionHold(){pendingSend=undefined;controlGeneration++;lastRender='';$('send').disabled=true;$('input').disabled=true;$('messages').replaceChildren();$('contacts').replaceChildren();system('删除预览请求状态待核对，为安全暂停显示与发送。');}
function render(s,readbackEpoch){if(state&&(s.conversation_id!==state.conversation_id||s.snapshot_version<state.snapshot_version||(!deletionBlocked(s)&&!deletionBlocked(state)&&s.controls.revision<state.controls.revision)))return false;if(readbackEpoch===deletionRequestEpoch&&!deletionRequestPending)deletionRequestUncertain=false;state=s;const blocked=sendingBlocked(),privacyState=s.deletion?.state;$('send').disabled=busy||blocked;$('input').disabled=blocked;if(blocked){pendingSend=undefined;controlGeneration++;if(privacyState==='cleaning'||privacyState==='deleted')$('input').value='';}const signature=JSON.stringify([s.conversation_id,s.controls,s.messages,s.turns,s.deletion,deletionRequestPending,deletionRequestUncertain]);if(signature===lastRender)return true;lastRender=signature;$('messages').replaceChildren();if(!blocked)for(const m of s.messages||[])$('messages').append(message(m));if(blocked)system(privacyState==='preview'?'本关系内容已暂停使用，等待删除确认。取消预览不会恢复已取消的回复。':privacyState==='deleted'?'本关系的在线可控记录已清除并退出。备份和外部副本状态请查看删除结果。':privacyState==='cleaning'?'删除处理中，内容保持停用；未完成的清理不会被当作成功。':'删除预览请求状态待核对，为安全暂停显示与发送。');else if(!(s.messages||[]).length)system('这是AI扮演的原创虚拟角色。可以从一句普通的话开始。');$('messages').scrollTop=$('messages').scrollHeight;$('contacts').replaceChildren();contact({name:'阿岚',preview:blocked?'关系内容已停用':s.messages?.at(-1)?.text||'我们慢慢聊',time:!blocked&&s.messages?.length?'刚刚':'',active:true});if(!blocked)renderTurns(s);else $('hint').textContent='关系内容已停用';return true;}

function contact(c){const b=document.createElement('button');b.className='contact'+(c.active?' active':'');b.append(avatar('character',c.avatar));const copy=document.createElement('div');copy.className='contact-copy';const line=document.createElement('div');line.className='contact-line';const name=document.createElement('span');name.className='contact-name';name.textContent=c.name;const time=document.createElement('time');time.textContent=c.time||'';line.append(name,time);const preview=document.createElement('div');preview.className='contact-preview';preview.textContent=c.preview;copy.append(line,preview);b.append(copy);b.onclick=()=>{if(!visual) $('input').focus();};$('contacts').append(b);}
function dialog(title,text){$('dialog-content').replaceChildren();const h=document.createElement('h2');h.textContent=title;const p=document.createElement('p');p.textContent=text;$('dialog-content').append(h,p);$('dialog-close').hidden=false;if(!$('dialog').open)$('dialog').showModal();}
let deletionPlan,deletionDialogBusy=false;
$('dialog-close').onclick=()=>{if(deletionPlan)void cancelDeletionPlan();else $('dialog').close();};
$('dialog').oncancel=e=>{if(deletionPlan){e.preventDefault();if(!deletionDialogBusy)void cancelDeletionPlan();}else if($('dialog-close').hidden)e.preventDefault();};
function placeholder(name){dialog(name,`${name}入口已保留，第一阶段暂未实现。`);}
for(const b of document.querySelectorAll('[data-icon]'))if(!['chat','menu','more','emoji'].includes(b.dataset.icon))b.onclick=()=>placeholder(b.title);
$('emoji').onclick=()=>{$('input').value+='😊';$('input').dispatchEvent(new Event('input'));$('input').focus();};
$('search').oninput=()=>{for(const c of document.querySelectorAll('.contact'))c.hidden=!c.textContent.includes($('search').value);};
document.querySelector('.add').onclick=()=>placeholder('新增聊天');
function controls(){if(sendingBlocked()){showDeletionStatus();return;}dialog('聊天设置','');const body=$('dialog-content');const summary=document.createElement('p');summary.className='status';summary.textContent=`长期记忆：${state?.controls.memory==='on'?'开启':'关闭'} · 扮演：${state?.controls.role==='active'?'继续':'暂停'}。主动联系未启用。`;body.append(summary);
 for(const [label,changes] of [['关闭长期记忆',{memory:'off'}],['开启长期记忆',{memory:'on'}],['暂停扮演',{role:'paused'}],['恢复扮演',{role:'active'}],['停止当前称呼',{nicknameState:'suspended'}],['只做朋友',{direction:'friends'}]]){const b=document.createElement('button');b.textContent=label;b.onclick=async()=>{controlGeneration++;try{render(await bridge.control(state.conversation_id,changes));$('dialog').close();system('设置已生效。关闭记忆不会自动删除以前保存的记录。');}catch(e){dialog('未能保存',friendly(e));}};body.append(b);}const p=document.createElement('p');p.className='status';p.textContent='记忆关闭时，聊天历史仅在当前进程使用；尚未处理的输入以安全系统密钥加密，最长暂存15分钟；必要拒绝和称呼边界仍保存。已有记录关闭后停止读取，重新开启可能重新读取。可预览并确认删除整段关系；指定范围删除与导出尚未提供；宿主与模型提供方可能保留副本。';body.append(p);const remove=document.createElement('button');remove.textContent='预览删除整段关系';remove.onclick=beginDeletion;body.append(remove);}
$('settings').onclick=controls;$('details').onclick=controls;
async function beginDeletion(){if(!state||deletionDialogBusy||sendingBlocked())return;deletionDialogBusy=true;deletionRequestPending=true;const requestEpoch=++deletionRequestEpoch;localDeletionHold();try{const response=await bridge.planDeletion(state.conversation_id);deletionRequestPending=false;if(!render(response))return;if(response.deletion?.state!=='preview'||!response.plan){showDeletionStatus();return;}deletionPlan=response.plan;showDeletionReview();}catch(e){deletionRequestPending=false;deletionRequestUncertain=true;deletionPlan=undefined;try{render(await bridge.snapshot(),requestEpoch);}catch{}dialog('删除预览状态待核对',friendly(e)+' 未确认前不会永久清理；读取当前状态成功前暂停显示和发送。');}finally{deletionDialogBusy=false;}}
function copyNotice(plan){return '范围：当前这段关系的聊天、来源、记忆、索引、待发送内容和缓存。确认后不可恢复；当前关系会退出。'+(plan?.backup_expires_at?'已有受控备份最晚到期：'+new Date(plan.backup_expires_at).toLocaleString()+'。':'没有登记的保留备份。')+'宿主历史、模型提供方及外部平台副本不在此清理范围；不承诺物理介质取证擦除。';}
function showDeletionReview(){const plan=deletionPlan;dialog('确认删除整段关系',copyNotice(plan));$('dialog-close').hidden=true;const body=$('dialog-content');const note=document.createElement('p');note.className='status';note.textContent='内容现已暂停使用。确认10分钟内有效；取消不会恢复已取消的回复。';body.append(note);const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';label.append(check,document.createTextNode(' 我理解不可恢复，确认删除本关系的本机可控数据'));body.append(label);const confirm=document.createElement('button');confirm.textContent='确认永久删除';confirm.disabled=true;check.onchange=()=>{confirm.disabled=!check.checked||deletionDialogBusy;};confirm.onclick=async()=>{if(!check.checked||deletionDialogBusy||deletionPlan!==plan)return;deletionDialogBusy=true;confirm.disabled=true;deletionPlan=undefined;try{render(await bridge.confirmDeletion(state.conversation_id,plan.plan_id,plan.digest,plan.confirmation_token));showDeletionStatus();}catch(e){try{render(await bridge.snapshot());}catch{}dialog('删除结果待核对',friendly(e)+' 请在设置查看当前状态，不会自动重新确认。');}finally{deletionDialogBusy=false;}};body.append(confirm);const cancel=document.createElement('button');cancel.textContent='取消删除预览';cancel.onclick=cancelDeletionPlan;body.append(cancel);}
async function cancelDeletionPlan(){if(deletionDialogBusy)return;const plan=deletionPlan||state?.deletion?.plan;if(!plan)return;deletionDialogBusy=true;try{render(await bridge.cancelDeletion(state.conversation_id,plan.plan_id));deletionPlan=undefined;$('dialog').close();}catch(e){dialog('未能取消预览',friendly(e));}finally{deletionDialogBusy=false;}}
function showDeletionStatus(){deletionPlan=undefined;const d=state?.deletion;if(!d){controls();return;}dialog(d.state==='deleted'?'删除结果':'数据清理状态',d.state==='deleted'?'在线可控记录已清除，本关系已退出。当前版本不提供旧关系恢复或新关系建立入口。':d.state==='preview'?'内容已暂停使用，尚未执行永久删除。可取消预览后重新核对范围。':'清理尚未全部完成，内容继续停用。只有全部验证通过才报告在线清除。');const body=$('dialog-content');const p=document.createElement('p');p.className='status';p.textContent=copyNotice(d.plan);body.append(p);if(d.state==='preview'){const cancel=document.createElement('button');cancel.textContent='取消删除预览';cancel.onclick=cancelDeletionPlan;body.append(cancel);}if(d.state==='cleaning'){const resume=document.createElement('button');resume.textContent='重试已确认的清理';resume.onclick=async()=>{resume.disabled=true;try{render(await bridge.resumeDeletion(state.conversation_id));showDeletionStatus();}catch(e){dialog('清理仍未完成',friendly(e));}};body.append(resume);}}
function friendly(e){const s=String(e);if(/DELETION_CONFIRMATION_EXPIRED/.test(s))return '删除确认已过期，内容仍停用。请取消预览后重新确认。';if(/DELETION_PREVIEW_STALE/.test(s))return '删除范围已有变化，旧确认无效。请取消预览后重新核对。';if(/RELATIONSHIP_SUPPRESSED|RELATIONSHIP_DELETED/.test(s))return '本关系内容已停用，不能继续聊天或使用旧授权。';if(/PRIVACY_AUTHORITY/.test(s))return '最新数据控制屏障无法验证，已停止读取和运行，没有恢复旧状态。';if(/HOST_CONTENT_BOUNDARY_UNAVAILABLE/.test(s))return '当前系统没有已验证的安全文件读取能力，已停止本轮。';if(/HOST_APP_ASSET_UNVERIFIED/.test(s))return '人物或Skill来源校验失败，已停止本轮，没有读取替代文件。';if(/HOST_PROVIDER_UNSUPPORTED/.test(s))return '这个模型接口尚未通过当前受限宿主的观测与权限验收，已停止本轮。';if(/HOST_AUTH_OR_API_ERROR/.test(s))return '模型宿主尚未登录，或提供方拒绝服务。当前Qwen模型配置尚未通过验证。没有生成角色回复。';if(/HOST_UNAVAILABLE/.test(s))return '受限Qwen宿主尚未配置或构建校验未通过，没有切换其他宿主。';if(/RESTORE_REQUIRES_NEW_INPUT|RESTORE_OUTPUT_UNACKNOWLEDGED/.test(s))return '恢复不会续跑旧轮次或重现未确认回复，请发送新内容；已经提交的操作不会自动重做。';if(/RECOVERY_REQUIRES_USER|OFF_INPUT_UNAVAILABLE|RESTORE_INPUT_UNAVAILABLE/.test(s))return '待处理的加密输入已过期或无法恢复。请取消对应失败消息后，再发送新内容。';if(/OFF_CACHE_UNAVAILABLE/.test(s))return '系统安全密钥存储不可用，关闭记忆时不能可靠收件。当前消息未接收；设置和取消仍可使用。';if(/QUEUE_FULL/.test(s))return '待处理消息已满，请取消一条或等待当前消息完成。';if(/UNKNOWN_OUTCOME|RECOVERY_REQUIRES_READBACK/.test(s))return '这一轮可能已有操作提交，结果待核对，不会自动重试。';if(/HOST_POLICY_UNVERIFIED|HOST_TOOL_BOUNDARY/.test(s))return '宿主工具权限不符合此客户端要求，已停止本轮。';if(/HOST_TIMEOUT|HOST_DISCONNECTED|SERVICE_DISCONNECTED/.test(s))return '宿主连接中断或超时。本轮没有确认回复，不会自动重发。';if(/NOT_AUTHORIZED|STALE_REVISION|BOUNDARY_VIOLATION/.test(s))return '本轮回复已因新的控制或边界变更而取消。';return '本轮未能完成，请稍后重试。';}
const acking=new Set();
function renderTurns(s){
 const active=(s.turns||[]).filter(t=>['accepted','queued','running','cancel_requested'].includes(t.status));
 $('hint').textContent=active.length?`待处理 ${active.length} 条`:'';
 for(const t of (s.turns||[]).filter(t=>!['completed','cancelled'].includes(t.status))){
  const row=document.createElement('div');row.className='system';
  const labels={accepted:'已接收',queued:'排队中',running:'正在回复',cancel_requested:'正在取消',failed:friendly(t.error_code),unknown_outcome:'操作结果待核对，不会自动重试'};
  row.textContent=(labels[t.status]||t.status)+(t.side_effect_outcome==='committed'?'；已提交的操作不会被取消撤销':'');
  if(['accepted','queued','running','failed','unknown_outcome'].includes(t.status)){const cancel=document.createElement('button');cancel.textContent='取消';cancel.onclick=async()=>{try{render(await bridge.cancel(s.conversation_id,t.turn_id));}catch(e){system(friendly(e),true);}};row.append(cancel);}
  $('messages').append(row);
 }
}
async function acknowledgeRendered(){
 const current=state;if(!current)return;
 for(const turn of current.turns||[]){const message=current.messages?.find(m=>m.id===turn.message_id&&m.status==='pending');if(!message||turn.cancelled||acking.has(message.id))continue;
  acking.add(message.id);const generation=controlGeneration;
  try{await new Promise(requestAnimationFrame);if(state.conversation_id===current.conversation_id&&generation===controlGeneration&&state.messages.some(m=>m.id===message.id)&&document.visibilityState==='visible'){render(await bridge.ack(current.conversation_id,turn.turn_id,message.id));}}
  catch(e){system(friendly(e),true);}finally{acking.delete(message.id);}
 }
}
let pendingSend;
async function send(){const text=$('input').value.trim();if(!text||busy||composing||!state||sendingBlocked())return;
 if(pendingSend&&pendingSend.text!==text){dialog('上一条仍待确认','请先恢复连接并确认上一条是否已接收，再修改内容发送。');return;}
 pendingSend??={turn_id:crypto.randomUUID(),text};const sending=pendingSend;busy=true;$('send').disabled=true;
 try{const s=await bridge.send(state.conversation_id,sending.turn_id,sending.text);pendingSend=undefined;if($('input').value.trim()===sending.text)$('input').value='';render(s);await acknowledgeRendered();}
 catch(e){
  // Keep the original turn ID on ambiguous transport failure. A retry is idempotent.
  if(!/SERVICE_TIMEOUT|SERVICE_DISCONNECTED/.test(String(e)))pendingSend=undefined;
  dialog(pendingSend?'接收状态待确认':'消息未接收',pendingSend?'连接中断，暂不能确认是否已接收。重新发送会沿用同一条消息标识，不会新建重复消息。':friendly(e));
 }finally{busy=false;$('send').disabled=sendingBlocked();document.querySelector('.composer').classList.toggle('has-text',!!$('input').value);$('input').focus();}}
let polling=false;
async function refresh(){if(visual||polling||!state)return;polling=true;const readbackEpoch=deletionRequestPending?undefined:deletionRequestEpoch;try{const snapshot=await bridge.snapshot();if(pendingSend&&snapshot.turns.some(t=>t.turn_id===pendingSend.turn_id)){if($('input').value.trim()===pendingSend.text)$('input').value='';pendingSend=undefined;}render(snapshot,readbackEpoch);await acknowledgeRendered();}catch(e){$('hint').textContent=friendly(e);}finally{polling=false;}}
$('send').onclick=send;$('input').oncompositionstart=()=>composing=true;$('input').oncompositionend=()=>composing=false;$('input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing&&!composing){e.preventDefault();send();}};$('input').oninput=()=>document.querySelector('.composer').classList.toggle('has-text',!!$('input').value);
function onboarding(){dialog('开始和阿岚聊天','这是AI扮演的29岁原创虚拟角色，面向成年人。日常文本可由已有模型宿主生成；主动联系、真实线下行动和媒体读取未启用。');$('dialog-close').hidden=true;const body=$('dialog-content');const checks=[];for(const text of ['我已满18岁','我已理解虚拟身份和数据说明，明确开始','开启长期记忆（可选，默认关闭）']){const label=document.createElement('label');const input=document.createElement('input');input.type='checkbox';label.append(input,document.createTextNode(' '+text));body.append(label);checks.push(input);}const note=document.createElement('p');note.className='status';note.textContent='开启时普通聊天原文滚动保留30天；有意义记忆及最小来源证据保留至本人删除；关闭时不保留长期聊天；待处理输入加密暂存最长15分钟，完成后移除。称呼、拒绝和必要控制独立保存。可确认删除整段关系，指定范围删除与数据导出尚未提供；当前候选仅用于测试。模型提供方及宿主可能保留副本；本机管理员可读取本机数据。';body.append(note);const b=document.createElement('button');b.className='primary';b.textContent='开始';b.onclick=async()=>{if(!checks[0].checked||!checks[1].checked)return;try{render(await bridge.start(true,true,checks[2].checked));$('dialog').close();$('input').focus();}catch(e){dialog('未能开始',friendly(e));}};body.append(b);}
async function init(){if(visual){const fixture=await import('./visual-fixture.js');fixture.draw({contact,message,$,avatar});return;}try{const s=await bridge.snapshot();render(s);if(!s.controls.started&&!deletionBlocked(s))onboarding();setInterval(refresh,500);}catch(e){system('本地数据服务未启动。',true);}}
init();
